package cn.edu.ustb.dm.dao;

import cn.edu.ustb.dm.model.AuthorInfo;
import cn.edu.ustb.dm.model.AuthorInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthorInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int countByExample(AuthorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int deleteByExample(AuthorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int deleteByPrimaryKey(Integer AUTHOR_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int insert(AuthorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int insertSelective(AuthorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    List<AuthorInfo> selectByExampleWithBLOBs(AuthorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    List<AuthorInfo> selectByExample(AuthorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    AuthorInfo selectByPrimaryKey(Integer AUTHOR_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int updateByExampleSelective(@Param("record") AuthorInfo record, @Param("example") AuthorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int updateByExampleWithBLOBs(@Param("record") AuthorInfo record, @Param("example") AuthorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int updateByExample(@Param("record") AuthorInfo record, @Param("example") AuthorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int updateByPrimaryKeySelective(AuthorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int updateByPrimaryKeyWithBLOBs(AuthorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int updateByPrimaryKey(AuthorInfo record);
}