package cn.edu.ustb.dm.dao;

import cn.edu.ustb.dm.model.BindingType;
import cn.edu.ustb.dm.model.BindingTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BindingTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table binding_type
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int countByExample(BindingTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table binding_type
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int deleteByExample(BindingTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table binding_type
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int deleteByPrimaryKey(Integer BINDING_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table binding_type
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int insert(BindingType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table binding_type
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int insertSelective(BindingType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table binding_type
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    List<BindingType> selectByExample(BindingTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table binding_type
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    BindingType selectByPrimaryKey(Integer BINDING_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table binding_type
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int updateByExampleSelective(@Param("record") BindingType record, @Param("example") BindingTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table binding_type
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int updateByExample(@Param("record") BindingType record, @Param("example") BindingTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table binding_type
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int updateByPrimaryKeySelective(BindingType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table binding_type
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int updateByPrimaryKey(BindingType record);
}