package cn.edu.ustb.dm.dao;

import cn.edu.ustb.dm.model.BookTagRelation;
import cn.edu.ustb.dm.model.BookTagRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookTagRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_tag_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int countByExample(BookTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_tag_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int deleteByExample(BookTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_tag_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int insert(BookTagRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_tag_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int insertSelective(BookTagRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_tag_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    List<BookTagRelation> selectByExample(BookTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_tag_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int updateByExampleSelective(@Param("record") BookTagRelation record, @Param("example") BookTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_tag_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int updateByExample(@Param("record") BookTagRelation record, @Param("example") BookTagRelationExample example);
}