package cn.edu.ustb.dm.dao;

import cn.edu.ustb.dm.model.BookAuthorInfo;
import cn.edu.ustb.dm.model.BookAuthorInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookAuthorInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int countByExample(BookAuthorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int deleteByExample(BookAuthorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int deleteByPrimaryKey(Integer book_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int insert(BookAuthorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int insertSelective(BookAuthorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    List<BookAuthorInfo> selectByExampleWithBLOBs(BookAuthorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    List<BookAuthorInfo> selectByExample(BookAuthorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    BookAuthorInfo selectByPrimaryKey(Integer book_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int updateByExampleSelective(@Param("record") BookAuthorInfo record, @Param("example") BookAuthorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int updateByExampleWithBLOBs(@Param("record") BookAuthorInfo record, @Param("example") BookAuthorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int updateByExample(@Param("record") BookAuthorInfo record, @Param("example") BookAuthorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int updateByPrimaryKeySelective(BookAuthorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int updateByPrimaryKeyWithBLOBs(BookAuthorInfo record);
}