package cn.edu.ustb.dm.dao;

import cn.edu.ustb.dm.model.BookAuthorRelation;
import cn.edu.ustb.dm.model.BookAuthorRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookAuthorRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int countByExample(BookAuthorRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int deleteByExample(BookAuthorRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int insert(BookAuthorRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int insertSelective(BookAuthorRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    List<BookAuthorRelation> selectByExample(BookAuthorRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int updateByExampleSelective(@Param("record") BookAuthorRelation record, @Param("example") BookAuthorRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    int updateByExample(@Param("record") BookAuthorRelation record, @Param("example") BookAuthorRelationExample example);
}