package cn.edu.ustb.dm.model;

public class BindingType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column binding_type.BINDING_ID
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer BINDING_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column binding_type.BINDING_NAME
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private String BINDING_NAME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column binding_type.BINDING_ID
     *
     * @return the value of binding_type.BINDING_ID
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getBINDING_ID() {
        return BINDING_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column binding_type.BINDING_ID
     *
     * @param BINDING_ID the value for binding_type.BINDING_ID
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setBINDING_ID(Integer BINDING_ID) {
        this.BINDING_ID = BINDING_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column binding_type.BINDING_NAME
     *
     * @return the value of binding_type.BINDING_NAME
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getBINDING_NAME() {
        return BINDING_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column binding_type.BINDING_NAME
     *
     * @param BINDING_NAME the value for binding_type.BINDING_NAME
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setBINDING_NAME(String BINDING_NAME) {
        this.BINDING_NAME = BINDING_NAME == null ? null : BINDING_NAME.trim();
    }
}