package cn.edu.ustb.dm.model;

public class BookPublishingInfoWithBLOBs extends BookPublishingInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_publishing_info.title
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_publishing_info.auther_name
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private String auther_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_publishing_info.description
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_publishing_info.directory
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private String directory;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_publishing_info.title
     *
     * @return the value of book_publishing_info.title
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_publishing_info.title
     *
     * @param title the value for book_publishing_info.title
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_publishing_info.auther_name
     *
     * @return the value of book_publishing_info.auther_name
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getAuther_name() {
        return auther_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_publishing_info.auther_name
     *
     * @param auther_name the value for book_publishing_info.auther_name
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setAuther_name(String auther_name) {
        this.auther_name = auther_name == null ? null : auther_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_publishing_info.description
     *
     * @return the value of book_publishing_info.description
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_publishing_info.description
     *
     * @param description the value for book_publishing_info.description
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_publishing_info.directory
     *
     * @return the value of book_publishing_info.directory
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getDirectory() {
        return directory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_publishing_info.directory
     *
     * @param directory the value for book_publishing_info.directory
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setDirectory(String directory) {
        this.directory = directory == null ? null : directory.trim();
    }
}