package cn.edu.ustb.dm.model;

public class BookOnlineInfoWithBLOBs extends BookOnlineInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_online_info.label
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_online_info.together_bought
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private String together_bought;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_online_info.label
     *
     * @return the value of book_online_info.label
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_online_info.label
     *
     * @param label the value for book_online_info.label
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_online_info.together_bought
     *
     * @return the value of book_online_info.together_bought
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getTogether_bought() {
        return together_bought;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_online_info.together_bought
     *
     * @param together_bought the value for book_online_info.together_bought
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setTogether_bought(String together_bought) {
        this.together_bought = together_bought == null ? null : together_bought.trim();
    }
}