package cn.edu.ustb.dm.model;

import java.util.Date;

public class BookInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.BOOK_ID
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer BOOK_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.ISBN
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private String ISBN;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.TITLE
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private String TITLE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.BINDING_ID
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer BINDING_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.LIST_PRICE
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer LIST_PRICE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.PAGE
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer PAGE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.PUBLISHER_ID
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer PUBLISHER_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.PUBLICATION_DATE
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Date PUBLICATION_DATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.TITLE_PAGE_IMAGES
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private String TITLE_PAGE_IMAGES;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.NUMBER_REVIEW
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer NUMBER_REVIEW;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.NUMBER_STAR5
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer NUMBER_STAR5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.NUMBER_STAR4
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer NUMBER_STAR4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.NUMBER_STAR3
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer NUMBER_STAR3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.NUMBER_STAR2
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer NUMBER_STAR2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.NUMBER_STAR1
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer NUMBER_STAR1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.NUMBER_TOREAD
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer NUMBER_TOREAD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.NUMBER_READING
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer NUMBER_READING;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.NUMBER_READED
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer NUMBER_READED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.BOOK_ID
     *
     * @return the value of book_info.BOOK_ID
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getBOOK_ID() {
        return BOOK_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.BOOK_ID
     *
     * @param BOOK_ID the value for book_info.BOOK_ID
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setBOOK_ID(Integer BOOK_ID) {
        this.BOOK_ID = BOOK_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.ISBN
     *
     * @return the value of book_info.ISBN
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getISBN() {
        return ISBN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.ISBN
     *
     * @param ISBN the value for book_info.ISBN
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setISBN(String ISBN) {
        this.ISBN = ISBN == null ? null : ISBN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.TITLE
     *
     * @return the value of book_info.TITLE
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getTITLE() {
        return TITLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.TITLE
     *
     * @param TITLE the value for book_info.TITLE
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setTITLE(String TITLE) {
        this.TITLE = TITLE == null ? null : TITLE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.BINDING_ID
     *
     * @return the value of book_info.BINDING_ID
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getBINDING_ID() {
        return BINDING_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.BINDING_ID
     *
     * @param BINDING_ID the value for book_info.BINDING_ID
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setBINDING_ID(Integer BINDING_ID) {
        this.BINDING_ID = BINDING_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.LIST_PRICE
     *
     * @return the value of book_info.LIST_PRICE
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getLIST_PRICE() {
        return LIST_PRICE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.LIST_PRICE
     *
     * @param LIST_PRICE the value for book_info.LIST_PRICE
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setLIST_PRICE(Integer LIST_PRICE) {
        this.LIST_PRICE = LIST_PRICE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.PAGE
     *
     * @return the value of book_info.PAGE
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getPAGE() {
        return PAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.PAGE
     *
     * @param PAGE the value for book_info.PAGE
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setPAGE(Integer PAGE) {
        this.PAGE = PAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.PUBLISHER_ID
     *
     * @return the value of book_info.PUBLISHER_ID
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getPUBLISHER_ID() {
        return PUBLISHER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.PUBLISHER_ID
     *
     * @param PUBLISHER_ID the value for book_info.PUBLISHER_ID
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setPUBLISHER_ID(Integer PUBLISHER_ID) {
        this.PUBLISHER_ID = PUBLISHER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.PUBLICATION_DATE
     *
     * @return the value of book_info.PUBLICATION_DATE
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Date getPUBLICATION_DATE() {
        return PUBLICATION_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.PUBLICATION_DATE
     *
     * @param PUBLICATION_DATE the value for book_info.PUBLICATION_DATE
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setPUBLICATION_DATE(Date PUBLICATION_DATE) {
        this.PUBLICATION_DATE = PUBLICATION_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.TITLE_PAGE_IMAGES
     *
     * @return the value of book_info.TITLE_PAGE_IMAGES
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getTITLE_PAGE_IMAGES() {
        return TITLE_PAGE_IMAGES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.TITLE_PAGE_IMAGES
     *
     * @param TITLE_PAGE_IMAGES the value for book_info.TITLE_PAGE_IMAGES
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setTITLE_PAGE_IMAGES(String TITLE_PAGE_IMAGES) {
        this.TITLE_PAGE_IMAGES = TITLE_PAGE_IMAGES == null ? null : TITLE_PAGE_IMAGES.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.NUMBER_REVIEW
     *
     * @return the value of book_info.NUMBER_REVIEW
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getNUMBER_REVIEW() {
        return NUMBER_REVIEW;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.NUMBER_REVIEW
     *
     * @param NUMBER_REVIEW the value for book_info.NUMBER_REVIEW
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setNUMBER_REVIEW(Integer NUMBER_REVIEW) {
        this.NUMBER_REVIEW = NUMBER_REVIEW;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.NUMBER_STAR5
     *
     * @return the value of book_info.NUMBER_STAR5
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getNUMBER_STAR5() {
        return NUMBER_STAR5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.NUMBER_STAR5
     *
     * @param NUMBER_STAR5 the value for book_info.NUMBER_STAR5
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setNUMBER_STAR5(Integer NUMBER_STAR5) {
        this.NUMBER_STAR5 = NUMBER_STAR5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.NUMBER_STAR4
     *
     * @return the value of book_info.NUMBER_STAR4
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getNUMBER_STAR4() {
        return NUMBER_STAR4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.NUMBER_STAR4
     *
     * @param NUMBER_STAR4 the value for book_info.NUMBER_STAR4
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setNUMBER_STAR4(Integer NUMBER_STAR4) {
        this.NUMBER_STAR4 = NUMBER_STAR4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.NUMBER_STAR3
     *
     * @return the value of book_info.NUMBER_STAR3
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getNUMBER_STAR3() {
        return NUMBER_STAR3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.NUMBER_STAR3
     *
     * @param NUMBER_STAR3 the value for book_info.NUMBER_STAR3
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setNUMBER_STAR3(Integer NUMBER_STAR3) {
        this.NUMBER_STAR3 = NUMBER_STAR3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.NUMBER_STAR2
     *
     * @return the value of book_info.NUMBER_STAR2
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getNUMBER_STAR2() {
        return NUMBER_STAR2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.NUMBER_STAR2
     *
     * @param NUMBER_STAR2 the value for book_info.NUMBER_STAR2
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setNUMBER_STAR2(Integer NUMBER_STAR2) {
        this.NUMBER_STAR2 = NUMBER_STAR2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.NUMBER_STAR1
     *
     * @return the value of book_info.NUMBER_STAR1
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getNUMBER_STAR1() {
        return NUMBER_STAR1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.NUMBER_STAR1
     *
     * @param NUMBER_STAR1 the value for book_info.NUMBER_STAR1
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setNUMBER_STAR1(Integer NUMBER_STAR1) {
        this.NUMBER_STAR1 = NUMBER_STAR1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.NUMBER_TOREAD
     *
     * @return the value of book_info.NUMBER_TOREAD
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getNUMBER_TOREAD() {
        return NUMBER_TOREAD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.NUMBER_TOREAD
     *
     * @param NUMBER_TOREAD the value for book_info.NUMBER_TOREAD
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setNUMBER_TOREAD(Integer NUMBER_TOREAD) {
        this.NUMBER_TOREAD = NUMBER_TOREAD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.NUMBER_READING
     *
     * @return the value of book_info.NUMBER_READING
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getNUMBER_READING() {
        return NUMBER_READING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.NUMBER_READING
     *
     * @param NUMBER_READING the value for book_info.NUMBER_READING
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setNUMBER_READING(Integer NUMBER_READING) {
        this.NUMBER_READING = NUMBER_READING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.NUMBER_READED
     *
     * @return the value of book_info.NUMBER_READED
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getNUMBER_READED() {
        return NUMBER_READED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.NUMBER_READED
     *
     * @param NUMBER_READED the value for book_info.NUMBER_READED
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setNUMBER_READED(Integer NUMBER_READED) {
        this.NUMBER_READED = NUMBER_READED;
    }
}