package cn.edu.ustb.dm.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class BookInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public BookInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andBOOK_IDIsNull() {
            addCriterion("BOOK_ID is null");
            return (Criteria) this;
        }

        public Criteria andBOOK_IDIsNotNull() {
            addCriterion("BOOK_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBOOK_IDEqualTo(Integer value) {
            addCriterion("BOOK_ID =", value, "BOOK_ID");
            return (Criteria) this;
        }

        public Criteria andBOOK_IDNotEqualTo(Integer value) {
            addCriterion("BOOK_ID <>", value, "BOOK_ID");
            return (Criteria) this;
        }

        public Criteria andBOOK_IDGreaterThan(Integer value) {
            addCriterion("BOOK_ID >", value, "BOOK_ID");
            return (Criteria) this;
        }

        public Criteria andBOOK_IDGreaterThanOrEqualTo(Integer value) {
            addCriterion("BOOK_ID >=", value, "BOOK_ID");
            return (Criteria) this;
        }

        public Criteria andBOOK_IDLessThan(Integer value) {
            addCriterion("BOOK_ID <", value, "BOOK_ID");
            return (Criteria) this;
        }

        public Criteria andBOOK_IDLessThanOrEqualTo(Integer value) {
            addCriterion("BOOK_ID <=", value, "BOOK_ID");
            return (Criteria) this;
        }

        public Criteria andBOOK_IDIn(List<Integer> values) {
            addCriterion("BOOK_ID in", values, "BOOK_ID");
            return (Criteria) this;
        }

        public Criteria andBOOK_IDNotIn(List<Integer> values) {
            addCriterion("BOOK_ID not in", values, "BOOK_ID");
            return (Criteria) this;
        }

        public Criteria andBOOK_IDBetween(Integer value1, Integer value2) {
            addCriterion("BOOK_ID between", value1, value2, "BOOK_ID");
            return (Criteria) this;
        }

        public Criteria andBOOK_IDNotBetween(Integer value1, Integer value2) {
            addCriterion("BOOK_ID not between", value1, value2, "BOOK_ID");
            return (Criteria) this;
        }

        public Criteria andISBNIsNull() {
            addCriterion("ISBN is null");
            return (Criteria) this;
        }

        public Criteria andISBNIsNotNull() {
            addCriterion("ISBN is not null");
            return (Criteria) this;
        }

        public Criteria andISBNEqualTo(String value) {
            addCriterion("ISBN =", value, "ISBN");
            return (Criteria) this;
        }

        public Criteria andISBNNotEqualTo(String value) {
            addCriterion("ISBN <>", value, "ISBN");
            return (Criteria) this;
        }

        public Criteria andISBNGreaterThan(String value) {
            addCriterion("ISBN >", value, "ISBN");
            return (Criteria) this;
        }

        public Criteria andISBNGreaterThanOrEqualTo(String value) {
            addCriterion("ISBN >=", value, "ISBN");
            return (Criteria) this;
        }

        public Criteria andISBNLessThan(String value) {
            addCriterion("ISBN <", value, "ISBN");
            return (Criteria) this;
        }

        public Criteria andISBNLessThanOrEqualTo(String value) {
            addCriterion("ISBN <=", value, "ISBN");
            return (Criteria) this;
        }

        public Criteria andISBNLike(String value) {
            addCriterion("ISBN like", value, "ISBN");
            return (Criteria) this;
        }

        public Criteria andISBNNotLike(String value) {
            addCriterion("ISBN not like", value, "ISBN");
            return (Criteria) this;
        }

        public Criteria andISBNIn(List<String> values) {
            addCriterion("ISBN in", values, "ISBN");
            return (Criteria) this;
        }

        public Criteria andISBNNotIn(List<String> values) {
            addCriterion("ISBN not in", values, "ISBN");
            return (Criteria) this;
        }

        public Criteria andISBNBetween(String value1, String value2) {
            addCriterion("ISBN between", value1, value2, "ISBN");
            return (Criteria) this;
        }

        public Criteria andISBNNotBetween(String value1, String value2) {
            addCriterion("ISBN not between", value1, value2, "ISBN");
            return (Criteria) this;
        }

        public Criteria andTITLEIsNull() {
            addCriterion("TITLE is null");
            return (Criteria) this;
        }

        public Criteria andTITLEIsNotNull() {
            addCriterion("TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andTITLEEqualTo(String value) {
            addCriterion("TITLE =", value, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLENotEqualTo(String value) {
            addCriterion("TITLE <>", value, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLEGreaterThan(String value) {
            addCriterion("TITLE >", value, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLEGreaterThanOrEqualTo(String value) {
            addCriterion("TITLE >=", value, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLELessThan(String value) {
            addCriterion("TITLE <", value, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLELessThanOrEqualTo(String value) {
            addCriterion("TITLE <=", value, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLELike(String value) {
            addCriterion("TITLE like", value, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLENotLike(String value) {
            addCriterion("TITLE not like", value, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLEIn(List<String> values) {
            addCriterion("TITLE in", values, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLENotIn(List<String> values) {
            addCriterion("TITLE not in", values, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLEBetween(String value1, String value2) {
            addCriterion("TITLE between", value1, value2, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLENotBetween(String value1, String value2) {
            addCriterion("TITLE not between", value1, value2, "TITLE");
            return (Criteria) this;
        }

        public Criteria andBINDING_IDIsNull() {
            addCriterion("BINDING_ID is null");
            return (Criteria) this;
        }

        public Criteria andBINDING_IDIsNotNull() {
            addCriterion("BINDING_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBINDING_IDEqualTo(Integer value) {
            addCriterion("BINDING_ID =", value, "BINDING_ID");
            return (Criteria) this;
        }

        public Criteria andBINDING_IDNotEqualTo(Integer value) {
            addCriterion("BINDING_ID <>", value, "BINDING_ID");
            return (Criteria) this;
        }

        public Criteria andBINDING_IDGreaterThan(Integer value) {
            addCriterion("BINDING_ID >", value, "BINDING_ID");
            return (Criteria) this;
        }

        public Criteria andBINDING_IDGreaterThanOrEqualTo(Integer value) {
            addCriterion("BINDING_ID >=", value, "BINDING_ID");
            return (Criteria) this;
        }

        public Criteria andBINDING_IDLessThan(Integer value) {
            addCriterion("BINDING_ID <", value, "BINDING_ID");
            return (Criteria) this;
        }

        public Criteria andBINDING_IDLessThanOrEqualTo(Integer value) {
            addCriterion("BINDING_ID <=", value, "BINDING_ID");
            return (Criteria) this;
        }

        public Criteria andBINDING_IDIn(List<Integer> values) {
            addCriterion("BINDING_ID in", values, "BINDING_ID");
            return (Criteria) this;
        }

        public Criteria andBINDING_IDNotIn(List<Integer> values) {
            addCriterion("BINDING_ID not in", values, "BINDING_ID");
            return (Criteria) this;
        }

        public Criteria andBINDING_IDBetween(Integer value1, Integer value2) {
            addCriterion("BINDING_ID between", value1, value2, "BINDING_ID");
            return (Criteria) this;
        }

        public Criteria andBINDING_IDNotBetween(Integer value1, Integer value2) {
            addCriterion("BINDING_ID not between", value1, value2, "BINDING_ID");
            return (Criteria) this;
        }

        public Criteria andLIST_PRICEIsNull() {
            addCriterion("LIST_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andLIST_PRICEIsNotNull() {
            addCriterion("LIST_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andLIST_PRICEEqualTo(Integer value) {
            addCriterion("LIST_PRICE =", value, "LIST_PRICE");
            return (Criteria) this;
        }

        public Criteria andLIST_PRICENotEqualTo(Integer value) {
            addCriterion("LIST_PRICE <>", value, "LIST_PRICE");
            return (Criteria) this;
        }

        public Criteria andLIST_PRICEGreaterThan(Integer value) {
            addCriterion("LIST_PRICE >", value, "LIST_PRICE");
            return (Criteria) this;
        }

        public Criteria andLIST_PRICEGreaterThanOrEqualTo(Integer value) {
            addCriterion("LIST_PRICE >=", value, "LIST_PRICE");
            return (Criteria) this;
        }

        public Criteria andLIST_PRICELessThan(Integer value) {
            addCriterion("LIST_PRICE <", value, "LIST_PRICE");
            return (Criteria) this;
        }

        public Criteria andLIST_PRICELessThanOrEqualTo(Integer value) {
            addCriterion("LIST_PRICE <=", value, "LIST_PRICE");
            return (Criteria) this;
        }

        public Criteria andLIST_PRICEIn(List<Integer> values) {
            addCriterion("LIST_PRICE in", values, "LIST_PRICE");
            return (Criteria) this;
        }

        public Criteria andLIST_PRICENotIn(List<Integer> values) {
            addCriterion("LIST_PRICE not in", values, "LIST_PRICE");
            return (Criteria) this;
        }

        public Criteria andLIST_PRICEBetween(Integer value1, Integer value2) {
            addCriterion("LIST_PRICE between", value1, value2, "LIST_PRICE");
            return (Criteria) this;
        }

        public Criteria andLIST_PRICENotBetween(Integer value1, Integer value2) {
            addCriterion("LIST_PRICE not between", value1, value2, "LIST_PRICE");
            return (Criteria) this;
        }

        public Criteria andPAGEIsNull() {
            addCriterion("PAGE is null");
            return (Criteria) this;
        }

        public Criteria andPAGEIsNotNull() {
            addCriterion("PAGE is not null");
            return (Criteria) this;
        }

        public Criteria andPAGEEqualTo(Integer value) {
            addCriterion("PAGE =", value, "PAGE");
            return (Criteria) this;
        }

        public Criteria andPAGENotEqualTo(Integer value) {
            addCriterion("PAGE <>", value, "PAGE");
            return (Criteria) this;
        }

        public Criteria andPAGEGreaterThan(Integer value) {
            addCriterion("PAGE >", value, "PAGE");
            return (Criteria) this;
        }

        public Criteria andPAGEGreaterThanOrEqualTo(Integer value) {
            addCriterion("PAGE >=", value, "PAGE");
            return (Criteria) this;
        }

        public Criteria andPAGELessThan(Integer value) {
            addCriterion("PAGE <", value, "PAGE");
            return (Criteria) this;
        }

        public Criteria andPAGELessThanOrEqualTo(Integer value) {
            addCriterion("PAGE <=", value, "PAGE");
            return (Criteria) this;
        }

        public Criteria andPAGEIn(List<Integer> values) {
            addCriterion("PAGE in", values, "PAGE");
            return (Criteria) this;
        }

        public Criteria andPAGENotIn(List<Integer> values) {
            addCriterion("PAGE not in", values, "PAGE");
            return (Criteria) this;
        }

        public Criteria andPAGEBetween(Integer value1, Integer value2) {
            addCriterion("PAGE between", value1, value2, "PAGE");
            return (Criteria) this;
        }

        public Criteria andPAGENotBetween(Integer value1, Integer value2) {
            addCriterion("PAGE not between", value1, value2, "PAGE");
            return (Criteria) this;
        }

        public Criteria andPUBLISHER_IDIsNull() {
            addCriterion("PUBLISHER_ID is null");
            return (Criteria) this;
        }

        public Criteria andPUBLISHER_IDIsNotNull() {
            addCriterion("PUBLISHER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPUBLISHER_IDEqualTo(Integer value) {
            addCriterion("PUBLISHER_ID =", value, "PUBLISHER_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLISHER_IDNotEqualTo(Integer value) {
            addCriterion("PUBLISHER_ID <>", value, "PUBLISHER_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLISHER_IDGreaterThan(Integer value) {
            addCriterion("PUBLISHER_ID >", value, "PUBLISHER_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLISHER_IDGreaterThanOrEqualTo(Integer value) {
            addCriterion("PUBLISHER_ID >=", value, "PUBLISHER_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLISHER_IDLessThan(Integer value) {
            addCriterion("PUBLISHER_ID <", value, "PUBLISHER_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLISHER_IDLessThanOrEqualTo(Integer value) {
            addCriterion("PUBLISHER_ID <=", value, "PUBLISHER_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLISHER_IDIn(List<Integer> values) {
            addCriterion("PUBLISHER_ID in", values, "PUBLISHER_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLISHER_IDNotIn(List<Integer> values) {
            addCriterion("PUBLISHER_ID not in", values, "PUBLISHER_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLISHER_IDBetween(Integer value1, Integer value2) {
            addCriterion("PUBLISHER_ID between", value1, value2, "PUBLISHER_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLISHER_IDNotBetween(Integer value1, Integer value2) {
            addCriterion("PUBLISHER_ID not between", value1, value2, "PUBLISHER_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLICATION_DATEIsNull() {
            addCriterion("PUBLICATION_DATE is null");
            return (Criteria) this;
        }

        public Criteria andPUBLICATION_DATEIsNotNull() {
            addCriterion("PUBLICATION_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andPUBLICATION_DATEEqualTo(Date value) {
            addCriterionForJDBCDate("PUBLICATION_DATE =", value, "PUBLICATION_DATE");
            return (Criteria) this;
        }

        public Criteria andPUBLICATION_DATENotEqualTo(Date value) {
            addCriterionForJDBCDate("PUBLICATION_DATE <>", value, "PUBLICATION_DATE");
            return (Criteria) this;
        }

        public Criteria andPUBLICATION_DATEGreaterThan(Date value) {
            addCriterionForJDBCDate("PUBLICATION_DATE >", value, "PUBLICATION_DATE");
            return (Criteria) this;
        }

        public Criteria andPUBLICATION_DATEGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("PUBLICATION_DATE >=", value, "PUBLICATION_DATE");
            return (Criteria) this;
        }

        public Criteria andPUBLICATION_DATELessThan(Date value) {
            addCriterionForJDBCDate("PUBLICATION_DATE <", value, "PUBLICATION_DATE");
            return (Criteria) this;
        }

        public Criteria andPUBLICATION_DATELessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("PUBLICATION_DATE <=", value, "PUBLICATION_DATE");
            return (Criteria) this;
        }

        public Criteria andPUBLICATION_DATEIn(List<Date> values) {
            addCriterionForJDBCDate("PUBLICATION_DATE in", values, "PUBLICATION_DATE");
            return (Criteria) this;
        }

        public Criteria andPUBLICATION_DATENotIn(List<Date> values) {
            addCriterionForJDBCDate("PUBLICATION_DATE not in", values, "PUBLICATION_DATE");
            return (Criteria) this;
        }

        public Criteria andPUBLICATION_DATEBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("PUBLICATION_DATE between", value1, value2, "PUBLICATION_DATE");
            return (Criteria) this;
        }

        public Criteria andPUBLICATION_DATENotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("PUBLICATION_DATE not between", value1, value2, "PUBLICATION_DATE");
            return (Criteria) this;
        }

        public Criteria andTITLE_PAGE_IMAGESIsNull() {
            addCriterion("TITLE_PAGE_IMAGES is null");
            return (Criteria) this;
        }

        public Criteria andTITLE_PAGE_IMAGESIsNotNull() {
            addCriterion("TITLE_PAGE_IMAGES is not null");
            return (Criteria) this;
        }

        public Criteria andTITLE_PAGE_IMAGESEqualTo(String value) {
            addCriterion("TITLE_PAGE_IMAGES =", value, "TITLE_PAGE_IMAGES");
            return (Criteria) this;
        }

        public Criteria andTITLE_PAGE_IMAGESNotEqualTo(String value) {
            addCriterion("TITLE_PAGE_IMAGES <>", value, "TITLE_PAGE_IMAGES");
            return (Criteria) this;
        }

        public Criteria andTITLE_PAGE_IMAGESGreaterThan(String value) {
            addCriterion("TITLE_PAGE_IMAGES >", value, "TITLE_PAGE_IMAGES");
            return (Criteria) this;
        }

        public Criteria andTITLE_PAGE_IMAGESGreaterThanOrEqualTo(String value) {
            addCriterion("TITLE_PAGE_IMAGES >=", value, "TITLE_PAGE_IMAGES");
            return (Criteria) this;
        }

        public Criteria andTITLE_PAGE_IMAGESLessThan(String value) {
            addCriterion("TITLE_PAGE_IMAGES <", value, "TITLE_PAGE_IMAGES");
            return (Criteria) this;
        }

        public Criteria andTITLE_PAGE_IMAGESLessThanOrEqualTo(String value) {
            addCriterion("TITLE_PAGE_IMAGES <=", value, "TITLE_PAGE_IMAGES");
            return (Criteria) this;
        }

        public Criteria andTITLE_PAGE_IMAGESLike(String value) {
            addCriterion("TITLE_PAGE_IMAGES like", value, "TITLE_PAGE_IMAGES");
            return (Criteria) this;
        }

        public Criteria andTITLE_PAGE_IMAGESNotLike(String value) {
            addCriterion("TITLE_PAGE_IMAGES not like", value, "TITLE_PAGE_IMAGES");
            return (Criteria) this;
        }

        public Criteria andTITLE_PAGE_IMAGESIn(List<String> values) {
            addCriterion("TITLE_PAGE_IMAGES in", values, "TITLE_PAGE_IMAGES");
            return (Criteria) this;
        }

        public Criteria andTITLE_PAGE_IMAGESNotIn(List<String> values) {
            addCriterion("TITLE_PAGE_IMAGES not in", values, "TITLE_PAGE_IMAGES");
            return (Criteria) this;
        }

        public Criteria andTITLE_PAGE_IMAGESBetween(String value1, String value2) {
            addCriterion("TITLE_PAGE_IMAGES between", value1, value2, "TITLE_PAGE_IMAGES");
            return (Criteria) this;
        }

        public Criteria andTITLE_PAGE_IMAGESNotBetween(String value1, String value2) {
            addCriterion("TITLE_PAGE_IMAGES not between", value1, value2, "TITLE_PAGE_IMAGES");
            return (Criteria) this;
        }

        public Criteria andNUMBER_REVIEWIsNull() {
            addCriterion("NUMBER_REVIEW is null");
            return (Criteria) this;
        }

        public Criteria andNUMBER_REVIEWIsNotNull() {
            addCriterion("NUMBER_REVIEW is not null");
            return (Criteria) this;
        }

        public Criteria andNUMBER_REVIEWEqualTo(Integer value) {
            addCriterion("NUMBER_REVIEW =", value, "NUMBER_REVIEW");
            return (Criteria) this;
        }

        public Criteria andNUMBER_REVIEWNotEqualTo(Integer value) {
            addCriterion("NUMBER_REVIEW <>", value, "NUMBER_REVIEW");
            return (Criteria) this;
        }

        public Criteria andNUMBER_REVIEWGreaterThan(Integer value) {
            addCriterion("NUMBER_REVIEW >", value, "NUMBER_REVIEW");
            return (Criteria) this;
        }

        public Criteria andNUMBER_REVIEWGreaterThanOrEqualTo(Integer value) {
            addCriterion("NUMBER_REVIEW >=", value, "NUMBER_REVIEW");
            return (Criteria) this;
        }

        public Criteria andNUMBER_REVIEWLessThan(Integer value) {
            addCriterion("NUMBER_REVIEW <", value, "NUMBER_REVIEW");
            return (Criteria) this;
        }

        public Criteria andNUMBER_REVIEWLessThanOrEqualTo(Integer value) {
            addCriterion("NUMBER_REVIEW <=", value, "NUMBER_REVIEW");
            return (Criteria) this;
        }

        public Criteria andNUMBER_REVIEWIn(List<Integer> values) {
            addCriterion("NUMBER_REVIEW in", values, "NUMBER_REVIEW");
            return (Criteria) this;
        }

        public Criteria andNUMBER_REVIEWNotIn(List<Integer> values) {
            addCriterion("NUMBER_REVIEW not in", values, "NUMBER_REVIEW");
            return (Criteria) this;
        }

        public Criteria andNUMBER_REVIEWBetween(Integer value1, Integer value2) {
            addCriterion("NUMBER_REVIEW between", value1, value2, "NUMBER_REVIEW");
            return (Criteria) this;
        }

        public Criteria andNUMBER_REVIEWNotBetween(Integer value1, Integer value2) {
            addCriterion("NUMBER_REVIEW not between", value1, value2, "NUMBER_REVIEW");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR5IsNull() {
            addCriterion("NUMBER_STAR5 is null");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR5IsNotNull() {
            addCriterion("NUMBER_STAR5 is not null");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR5EqualTo(Integer value) {
            addCriterion("NUMBER_STAR5 =", value, "NUMBER_STAR5");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR5NotEqualTo(Integer value) {
            addCriterion("NUMBER_STAR5 <>", value, "NUMBER_STAR5");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR5GreaterThan(Integer value) {
            addCriterion("NUMBER_STAR5 >", value, "NUMBER_STAR5");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR5GreaterThanOrEqualTo(Integer value) {
            addCriterion("NUMBER_STAR5 >=", value, "NUMBER_STAR5");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR5LessThan(Integer value) {
            addCriterion("NUMBER_STAR5 <", value, "NUMBER_STAR5");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR5LessThanOrEqualTo(Integer value) {
            addCriterion("NUMBER_STAR5 <=", value, "NUMBER_STAR5");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR5In(List<Integer> values) {
            addCriterion("NUMBER_STAR5 in", values, "NUMBER_STAR5");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR5NotIn(List<Integer> values) {
            addCriterion("NUMBER_STAR5 not in", values, "NUMBER_STAR5");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR5Between(Integer value1, Integer value2) {
            addCriterion("NUMBER_STAR5 between", value1, value2, "NUMBER_STAR5");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR5NotBetween(Integer value1, Integer value2) {
            addCriterion("NUMBER_STAR5 not between", value1, value2, "NUMBER_STAR5");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR4IsNull() {
            addCriterion("NUMBER_STAR4 is null");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR4IsNotNull() {
            addCriterion("NUMBER_STAR4 is not null");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR4EqualTo(Integer value) {
            addCriterion("NUMBER_STAR4 =", value, "NUMBER_STAR4");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR4NotEqualTo(Integer value) {
            addCriterion("NUMBER_STAR4 <>", value, "NUMBER_STAR4");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR4GreaterThan(Integer value) {
            addCriterion("NUMBER_STAR4 >", value, "NUMBER_STAR4");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR4GreaterThanOrEqualTo(Integer value) {
            addCriterion("NUMBER_STAR4 >=", value, "NUMBER_STAR4");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR4LessThan(Integer value) {
            addCriterion("NUMBER_STAR4 <", value, "NUMBER_STAR4");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR4LessThanOrEqualTo(Integer value) {
            addCriterion("NUMBER_STAR4 <=", value, "NUMBER_STAR4");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR4In(List<Integer> values) {
            addCriterion("NUMBER_STAR4 in", values, "NUMBER_STAR4");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR4NotIn(List<Integer> values) {
            addCriterion("NUMBER_STAR4 not in", values, "NUMBER_STAR4");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR4Between(Integer value1, Integer value2) {
            addCriterion("NUMBER_STAR4 between", value1, value2, "NUMBER_STAR4");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR4NotBetween(Integer value1, Integer value2) {
            addCriterion("NUMBER_STAR4 not between", value1, value2, "NUMBER_STAR4");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR3IsNull() {
            addCriterion("NUMBER_STAR3 is null");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR3IsNotNull() {
            addCriterion("NUMBER_STAR3 is not null");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR3EqualTo(Integer value) {
            addCriterion("NUMBER_STAR3 =", value, "NUMBER_STAR3");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR3NotEqualTo(Integer value) {
            addCriterion("NUMBER_STAR3 <>", value, "NUMBER_STAR3");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR3GreaterThan(Integer value) {
            addCriterion("NUMBER_STAR3 >", value, "NUMBER_STAR3");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR3GreaterThanOrEqualTo(Integer value) {
            addCriterion("NUMBER_STAR3 >=", value, "NUMBER_STAR3");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR3LessThan(Integer value) {
            addCriterion("NUMBER_STAR3 <", value, "NUMBER_STAR3");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR3LessThanOrEqualTo(Integer value) {
            addCriterion("NUMBER_STAR3 <=", value, "NUMBER_STAR3");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR3In(List<Integer> values) {
            addCriterion("NUMBER_STAR3 in", values, "NUMBER_STAR3");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR3NotIn(List<Integer> values) {
            addCriterion("NUMBER_STAR3 not in", values, "NUMBER_STAR3");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR3Between(Integer value1, Integer value2) {
            addCriterion("NUMBER_STAR3 between", value1, value2, "NUMBER_STAR3");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR3NotBetween(Integer value1, Integer value2) {
            addCriterion("NUMBER_STAR3 not between", value1, value2, "NUMBER_STAR3");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR2IsNull() {
            addCriterion("NUMBER_STAR2 is null");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR2IsNotNull() {
            addCriterion("NUMBER_STAR2 is not null");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR2EqualTo(Integer value) {
            addCriterion("NUMBER_STAR2 =", value, "NUMBER_STAR2");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR2NotEqualTo(Integer value) {
            addCriterion("NUMBER_STAR2 <>", value, "NUMBER_STAR2");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR2GreaterThan(Integer value) {
            addCriterion("NUMBER_STAR2 >", value, "NUMBER_STAR2");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR2GreaterThanOrEqualTo(Integer value) {
            addCriterion("NUMBER_STAR2 >=", value, "NUMBER_STAR2");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR2LessThan(Integer value) {
            addCriterion("NUMBER_STAR2 <", value, "NUMBER_STAR2");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR2LessThanOrEqualTo(Integer value) {
            addCriterion("NUMBER_STAR2 <=", value, "NUMBER_STAR2");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR2In(List<Integer> values) {
            addCriterion("NUMBER_STAR2 in", values, "NUMBER_STAR2");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR2NotIn(List<Integer> values) {
            addCriterion("NUMBER_STAR2 not in", values, "NUMBER_STAR2");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR2Between(Integer value1, Integer value2) {
            addCriterion("NUMBER_STAR2 between", value1, value2, "NUMBER_STAR2");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR2NotBetween(Integer value1, Integer value2) {
            addCriterion("NUMBER_STAR2 not between", value1, value2, "NUMBER_STAR2");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR1IsNull() {
            addCriterion("NUMBER_STAR1 is null");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR1IsNotNull() {
            addCriterion("NUMBER_STAR1 is not null");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR1EqualTo(Integer value) {
            addCriterion("NUMBER_STAR1 =", value, "NUMBER_STAR1");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR1NotEqualTo(Integer value) {
            addCriterion("NUMBER_STAR1 <>", value, "NUMBER_STAR1");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR1GreaterThan(Integer value) {
            addCriterion("NUMBER_STAR1 >", value, "NUMBER_STAR1");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR1GreaterThanOrEqualTo(Integer value) {
            addCriterion("NUMBER_STAR1 >=", value, "NUMBER_STAR1");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR1LessThan(Integer value) {
            addCriterion("NUMBER_STAR1 <", value, "NUMBER_STAR1");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR1LessThanOrEqualTo(Integer value) {
            addCriterion("NUMBER_STAR1 <=", value, "NUMBER_STAR1");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR1In(List<Integer> values) {
            addCriterion("NUMBER_STAR1 in", values, "NUMBER_STAR1");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR1NotIn(List<Integer> values) {
            addCriterion("NUMBER_STAR1 not in", values, "NUMBER_STAR1");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR1Between(Integer value1, Integer value2) {
            addCriterion("NUMBER_STAR1 between", value1, value2, "NUMBER_STAR1");
            return (Criteria) this;
        }

        public Criteria andNUMBER_STAR1NotBetween(Integer value1, Integer value2) {
            addCriterion("NUMBER_STAR1 not between", value1, value2, "NUMBER_STAR1");
            return (Criteria) this;
        }

        public Criteria andNUMBER_TOREADIsNull() {
            addCriterion("NUMBER_TOREAD is null");
            return (Criteria) this;
        }

        public Criteria andNUMBER_TOREADIsNotNull() {
            addCriterion("NUMBER_TOREAD is not null");
            return (Criteria) this;
        }

        public Criteria andNUMBER_TOREADEqualTo(Integer value) {
            addCriterion("NUMBER_TOREAD =", value, "NUMBER_TOREAD");
            return (Criteria) this;
        }

        public Criteria andNUMBER_TOREADNotEqualTo(Integer value) {
            addCriterion("NUMBER_TOREAD <>", value, "NUMBER_TOREAD");
            return (Criteria) this;
        }

        public Criteria andNUMBER_TOREADGreaterThan(Integer value) {
            addCriterion("NUMBER_TOREAD >", value, "NUMBER_TOREAD");
            return (Criteria) this;
        }

        public Criteria andNUMBER_TOREADGreaterThanOrEqualTo(Integer value) {
            addCriterion("NUMBER_TOREAD >=", value, "NUMBER_TOREAD");
            return (Criteria) this;
        }

        public Criteria andNUMBER_TOREADLessThan(Integer value) {
            addCriterion("NUMBER_TOREAD <", value, "NUMBER_TOREAD");
            return (Criteria) this;
        }

        public Criteria andNUMBER_TOREADLessThanOrEqualTo(Integer value) {
            addCriterion("NUMBER_TOREAD <=", value, "NUMBER_TOREAD");
            return (Criteria) this;
        }

        public Criteria andNUMBER_TOREADIn(List<Integer> values) {
            addCriterion("NUMBER_TOREAD in", values, "NUMBER_TOREAD");
            return (Criteria) this;
        }

        public Criteria andNUMBER_TOREADNotIn(List<Integer> values) {
            addCriterion("NUMBER_TOREAD not in", values, "NUMBER_TOREAD");
            return (Criteria) this;
        }

        public Criteria andNUMBER_TOREADBetween(Integer value1, Integer value2) {
            addCriterion("NUMBER_TOREAD between", value1, value2, "NUMBER_TOREAD");
            return (Criteria) this;
        }

        public Criteria andNUMBER_TOREADNotBetween(Integer value1, Integer value2) {
            addCriterion("NUMBER_TOREAD not between", value1, value2, "NUMBER_TOREAD");
            return (Criteria) this;
        }

        public Criteria andNUMBER_READINGIsNull() {
            addCriterion("NUMBER_READING is null");
            return (Criteria) this;
        }

        public Criteria andNUMBER_READINGIsNotNull() {
            addCriterion("NUMBER_READING is not null");
            return (Criteria) this;
        }

        public Criteria andNUMBER_READINGEqualTo(Integer value) {
            addCriterion("NUMBER_READING =", value, "NUMBER_READING");
            return (Criteria) this;
        }

        public Criteria andNUMBER_READINGNotEqualTo(Integer value) {
            addCriterion("NUMBER_READING <>", value, "NUMBER_READING");
            return (Criteria) this;
        }

        public Criteria andNUMBER_READINGGreaterThan(Integer value) {
            addCriterion("NUMBER_READING >", value, "NUMBER_READING");
            return (Criteria) this;
        }

        public Criteria andNUMBER_READINGGreaterThanOrEqualTo(Integer value) {
            addCriterion("NUMBER_READING >=", value, "NUMBER_READING");
            return (Criteria) this;
        }

        public Criteria andNUMBER_READINGLessThan(Integer value) {
            addCriterion("NUMBER_READING <", value, "NUMBER_READING");
            return (Criteria) this;
        }

        public Criteria andNUMBER_READINGLessThanOrEqualTo(Integer value) {
            addCriterion("NUMBER_READING <=", value, "NUMBER_READING");
            return (Criteria) this;
        }

        public Criteria andNUMBER_READINGIn(List<Integer> values) {
            addCriterion("NUMBER_READING in", values, "NUMBER_READING");
            return (Criteria) this;
        }

        public Criteria andNUMBER_READINGNotIn(List<Integer> values) {
            addCriterion("NUMBER_READING not in", values, "NUMBER_READING");
            return (Criteria) this;
        }

        public Criteria andNUMBER_READINGBetween(Integer value1, Integer value2) {
            addCriterion("NUMBER_READING between", value1, value2, "NUMBER_READING");
            return (Criteria) this;
        }

        public Criteria andNUMBER_READINGNotBetween(Integer value1, Integer value2) {
            addCriterion("NUMBER_READING not between", value1, value2, "NUMBER_READING");
            return (Criteria) this;
        }

        public Criteria andNUMBER_READEDIsNull() {
            addCriterion("NUMBER_READED is null");
            return (Criteria) this;
        }

        public Criteria andNUMBER_READEDIsNotNull() {
            addCriterion("NUMBER_READED is not null");
            return (Criteria) this;
        }

        public Criteria andNUMBER_READEDEqualTo(Integer value) {
            addCriterion("NUMBER_READED =", value, "NUMBER_READED");
            return (Criteria) this;
        }

        public Criteria andNUMBER_READEDNotEqualTo(Integer value) {
            addCriterion("NUMBER_READED <>", value, "NUMBER_READED");
            return (Criteria) this;
        }

        public Criteria andNUMBER_READEDGreaterThan(Integer value) {
            addCriterion("NUMBER_READED >", value, "NUMBER_READED");
            return (Criteria) this;
        }

        public Criteria andNUMBER_READEDGreaterThanOrEqualTo(Integer value) {
            addCriterion("NUMBER_READED >=", value, "NUMBER_READED");
            return (Criteria) this;
        }

        public Criteria andNUMBER_READEDLessThan(Integer value) {
            addCriterion("NUMBER_READED <", value, "NUMBER_READED");
            return (Criteria) this;
        }

        public Criteria andNUMBER_READEDLessThanOrEqualTo(Integer value) {
            addCriterion("NUMBER_READED <=", value, "NUMBER_READED");
            return (Criteria) this;
        }

        public Criteria andNUMBER_READEDIn(List<Integer> values) {
            addCriterion("NUMBER_READED in", values, "NUMBER_READED");
            return (Criteria) this;
        }

        public Criteria andNUMBER_READEDNotIn(List<Integer> values) {
            addCriterion("NUMBER_READED not in", values, "NUMBER_READED");
            return (Criteria) this;
        }

        public Criteria andNUMBER_READEDBetween(Integer value1, Integer value2) {
            addCriterion("NUMBER_READED between", value1, value2, "NUMBER_READED");
            return (Criteria) this;
        }

        public Criteria andNUMBER_READEDNotBetween(Integer value1, Integer value2) {
            addCriterion("NUMBER_READED not between", value1, value2, "NUMBER_READED");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_info
     *
     * @mbggenerated do_not_delete_during_merge Sun May 19 11:22:56 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}