package cn.edu.ustb.dm.model;

import java.util.ArrayList;
import java.util.List;

public class BookOnlineInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_online_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_online_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_online_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_online_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public BookOnlineInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_online_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_online_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_online_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_online_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_online_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_online_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_online_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_online_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_online_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_online_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_online_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBook_idIsNull() {
            addCriterion("book_id is null");
            return (Criteria) this;
        }

        public Criteria andBook_idIsNotNull() {
            addCriterion("book_id is not null");
            return (Criteria) this;
        }

        public Criteria andBook_idEqualTo(Integer value) {
            addCriterion("book_id =", value, "book_id");
            return (Criteria) this;
        }

        public Criteria andBook_idNotEqualTo(Integer value) {
            addCriterion("book_id <>", value, "book_id");
            return (Criteria) this;
        }

        public Criteria andBook_idGreaterThan(Integer value) {
            addCriterion("book_id >", value, "book_id");
            return (Criteria) this;
        }

        public Criteria andBook_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("book_id >=", value, "book_id");
            return (Criteria) this;
        }

        public Criteria andBook_idLessThan(Integer value) {
            addCriterion("book_id <", value, "book_id");
            return (Criteria) this;
        }

        public Criteria andBook_idLessThanOrEqualTo(Integer value) {
            addCriterion("book_id <=", value, "book_id");
            return (Criteria) this;
        }

        public Criteria andBook_idIn(List<Integer> values) {
            addCriterion("book_id in", values, "book_id");
            return (Criteria) this;
        }

        public Criteria andBook_idNotIn(List<Integer> values) {
            addCriterion("book_id not in", values, "book_id");
            return (Criteria) this;
        }

        public Criteria andBook_idBetween(Integer value1, Integer value2) {
            addCriterion("book_id between", value1, value2, "book_id");
            return (Criteria) this;
        }

        public Criteria andBook_idNotBetween(Integer value1, Integer value2) {
            addCriterion("book_id not between", value1, value2, "book_id");
            return (Criteria) this;
        }

        public Criteria andNumber_reviewIsNull() {
            addCriterion("number_review is null");
            return (Criteria) this;
        }

        public Criteria andNumber_reviewIsNotNull() {
            addCriterion("number_review is not null");
            return (Criteria) this;
        }

        public Criteria andNumber_reviewEqualTo(Integer value) {
            addCriterion("number_review =", value, "number_review");
            return (Criteria) this;
        }

        public Criteria andNumber_reviewNotEqualTo(Integer value) {
            addCriterion("number_review <>", value, "number_review");
            return (Criteria) this;
        }

        public Criteria andNumber_reviewGreaterThan(Integer value) {
            addCriterion("number_review >", value, "number_review");
            return (Criteria) this;
        }

        public Criteria andNumber_reviewGreaterThanOrEqualTo(Integer value) {
            addCriterion("number_review >=", value, "number_review");
            return (Criteria) this;
        }

        public Criteria andNumber_reviewLessThan(Integer value) {
            addCriterion("number_review <", value, "number_review");
            return (Criteria) this;
        }

        public Criteria andNumber_reviewLessThanOrEqualTo(Integer value) {
            addCriterion("number_review <=", value, "number_review");
            return (Criteria) this;
        }

        public Criteria andNumber_reviewIn(List<Integer> values) {
            addCriterion("number_review in", values, "number_review");
            return (Criteria) this;
        }

        public Criteria andNumber_reviewNotIn(List<Integer> values) {
            addCriterion("number_review not in", values, "number_review");
            return (Criteria) this;
        }

        public Criteria andNumber_reviewBetween(Integer value1, Integer value2) {
            addCriterion("number_review between", value1, value2, "number_review");
            return (Criteria) this;
        }

        public Criteria andNumber_reviewNotBetween(Integer value1, Integer value2) {
            addCriterion("number_review not between", value1, value2, "number_review");
            return (Criteria) this;
        }

        public Criteria andNumber_star5IsNull() {
            addCriterion("number_star5 is null");
            return (Criteria) this;
        }

        public Criteria andNumber_star5IsNotNull() {
            addCriterion("number_star5 is not null");
            return (Criteria) this;
        }

        public Criteria andNumber_star5EqualTo(Integer value) {
            addCriterion("number_star5 =", value, "number_star5");
            return (Criteria) this;
        }

        public Criteria andNumber_star5NotEqualTo(Integer value) {
            addCriterion("number_star5 <>", value, "number_star5");
            return (Criteria) this;
        }

        public Criteria andNumber_star5GreaterThan(Integer value) {
            addCriterion("number_star5 >", value, "number_star5");
            return (Criteria) this;
        }

        public Criteria andNumber_star5GreaterThanOrEqualTo(Integer value) {
            addCriterion("number_star5 >=", value, "number_star5");
            return (Criteria) this;
        }

        public Criteria andNumber_star5LessThan(Integer value) {
            addCriterion("number_star5 <", value, "number_star5");
            return (Criteria) this;
        }

        public Criteria andNumber_star5LessThanOrEqualTo(Integer value) {
            addCriterion("number_star5 <=", value, "number_star5");
            return (Criteria) this;
        }

        public Criteria andNumber_star5In(List<Integer> values) {
            addCriterion("number_star5 in", values, "number_star5");
            return (Criteria) this;
        }

        public Criteria andNumber_star5NotIn(List<Integer> values) {
            addCriterion("number_star5 not in", values, "number_star5");
            return (Criteria) this;
        }

        public Criteria andNumber_star5Between(Integer value1, Integer value2) {
            addCriterion("number_star5 between", value1, value2, "number_star5");
            return (Criteria) this;
        }

        public Criteria andNumber_star5NotBetween(Integer value1, Integer value2) {
            addCriterion("number_star5 not between", value1, value2, "number_star5");
            return (Criteria) this;
        }

        public Criteria andNumber_star4IsNull() {
            addCriterion("number_star4 is null");
            return (Criteria) this;
        }

        public Criteria andNumber_star4IsNotNull() {
            addCriterion("number_star4 is not null");
            return (Criteria) this;
        }

        public Criteria andNumber_star4EqualTo(Integer value) {
            addCriterion("number_star4 =", value, "number_star4");
            return (Criteria) this;
        }

        public Criteria andNumber_star4NotEqualTo(Integer value) {
            addCriterion("number_star4 <>", value, "number_star4");
            return (Criteria) this;
        }

        public Criteria andNumber_star4GreaterThan(Integer value) {
            addCriterion("number_star4 >", value, "number_star4");
            return (Criteria) this;
        }

        public Criteria andNumber_star4GreaterThanOrEqualTo(Integer value) {
            addCriterion("number_star4 >=", value, "number_star4");
            return (Criteria) this;
        }

        public Criteria andNumber_star4LessThan(Integer value) {
            addCriterion("number_star4 <", value, "number_star4");
            return (Criteria) this;
        }

        public Criteria andNumber_star4LessThanOrEqualTo(Integer value) {
            addCriterion("number_star4 <=", value, "number_star4");
            return (Criteria) this;
        }

        public Criteria andNumber_star4In(List<Integer> values) {
            addCriterion("number_star4 in", values, "number_star4");
            return (Criteria) this;
        }

        public Criteria andNumber_star4NotIn(List<Integer> values) {
            addCriterion("number_star4 not in", values, "number_star4");
            return (Criteria) this;
        }

        public Criteria andNumber_star4Between(Integer value1, Integer value2) {
            addCriterion("number_star4 between", value1, value2, "number_star4");
            return (Criteria) this;
        }

        public Criteria andNumber_star4NotBetween(Integer value1, Integer value2) {
            addCriterion("number_star4 not between", value1, value2, "number_star4");
            return (Criteria) this;
        }

        public Criteria andNumber_star3IsNull() {
            addCriterion("number_star3 is null");
            return (Criteria) this;
        }

        public Criteria andNumber_star3IsNotNull() {
            addCriterion("number_star3 is not null");
            return (Criteria) this;
        }

        public Criteria andNumber_star3EqualTo(Integer value) {
            addCriterion("number_star3 =", value, "number_star3");
            return (Criteria) this;
        }

        public Criteria andNumber_star3NotEqualTo(Integer value) {
            addCriterion("number_star3 <>", value, "number_star3");
            return (Criteria) this;
        }

        public Criteria andNumber_star3GreaterThan(Integer value) {
            addCriterion("number_star3 >", value, "number_star3");
            return (Criteria) this;
        }

        public Criteria andNumber_star3GreaterThanOrEqualTo(Integer value) {
            addCriterion("number_star3 >=", value, "number_star3");
            return (Criteria) this;
        }

        public Criteria andNumber_star3LessThan(Integer value) {
            addCriterion("number_star3 <", value, "number_star3");
            return (Criteria) this;
        }

        public Criteria andNumber_star3LessThanOrEqualTo(Integer value) {
            addCriterion("number_star3 <=", value, "number_star3");
            return (Criteria) this;
        }

        public Criteria andNumber_star3In(List<Integer> values) {
            addCriterion("number_star3 in", values, "number_star3");
            return (Criteria) this;
        }

        public Criteria andNumber_star3NotIn(List<Integer> values) {
            addCriterion("number_star3 not in", values, "number_star3");
            return (Criteria) this;
        }

        public Criteria andNumber_star3Between(Integer value1, Integer value2) {
            addCriterion("number_star3 between", value1, value2, "number_star3");
            return (Criteria) this;
        }

        public Criteria andNumber_star3NotBetween(Integer value1, Integer value2) {
            addCriterion("number_star3 not between", value1, value2, "number_star3");
            return (Criteria) this;
        }

        public Criteria andNumber_star2IsNull() {
            addCriterion("number_star2 is null");
            return (Criteria) this;
        }

        public Criteria andNumber_star2IsNotNull() {
            addCriterion("number_star2 is not null");
            return (Criteria) this;
        }

        public Criteria andNumber_star2EqualTo(Integer value) {
            addCriterion("number_star2 =", value, "number_star2");
            return (Criteria) this;
        }

        public Criteria andNumber_star2NotEqualTo(Integer value) {
            addCriterion("number_star2 <>", value, "number_star2");
            return (Criteria) this;
        }

        public Criteria andNumber_star2GreaterThan(Integer value) {
            addCriterion("number_star2 >", value, "number_star2");
            return (Criteria) this;
        }

        public Criteria andNumber_star2GreaterThanOrEqualTo(Integer value) {
            addCriterion("number_star2 >=", value, "number_star2");
            return (Criteria) this;
        }

        public Criteria andNumber_star2LessThan(Integer value) {
            addCriterion("number_star2 <", value, "number_star2");
            return (Criteria) this;
        }

        public Criteria andNumber_star2LessThanOrEqualTo(Integer value) {
            addCriterion("number_star2 <=", value, "number_star2");
            return (Criteria) this;
        }

        public Criteria andNumber_star2In(List<Integer> values) {
            addCriterion("number_star2 in", values, "number_star2");
            return (Criteria) this;
        }

        public Criteria andNumber_star2NotIn(List<Integer> values) {
            addCriterion("number_star2 not in", values, "number_star2");
            return (Criteria) this;
        }

        public Criteria andNumber_star2Between(Integer value1, Integer value2) {
            addCriterion("number_star2 between", value1, value2, "number_star2");
            return (Criteria) this;
        }

        public Criteria andNumber_star2NotBetween(Integer value1, Integer value2) {
            addCriterion("number_star2 not between", value1, value2, "number_star2");
            return (Criteria) this;
        }

        public Criteria andNumber_star1IsNull() {
            addCriterion("number_star1 is null");
            return (Criteria) this;
        }

        public Criteria andNumber_star1IsNotNull() {
            addCriterion("number_star1 is not null");
            return (Criteria) this;
        }

        public Criteria andNumber_star1EqualTo(Integer value) {
            addCriterion("number_star1 =", value, "number_star1");
            return (Criteria) this;
        }

        public Criteria andNumber_star1NotEqualTo(Integer value) {
            addCriterion("number_star1 <>", value, "number_star1");
            return (Criteria) this;
        }

        public Criteria andNumber_star1GreaterThan(Integer value) {
            addCriterion("number_star1 >", value, "number_star1");
            return (Criteria) this;
        }

        public Criteria andNumber_star1GreaterThanOrEqualTo(Integer value) {
            addCriterion("number_star1 >=", value, "number_star1");
            return (Criteria) this;
        }

        public Criteria andNumber_star1LessThan(Integer value) {
            addCriterion("number_star1 <", value, "number_star1");
            return (Criteria) this;
        }

        public Criteria andNumber_star1LessThanOrEqualTo(Integer value) {
            addCriterion("number_star1 <=", value, "number_star1");
            return (Criteria) this;
        }

        public Criteria andNumber_star1In(List<Integer> values) {
            addCriterion("number_star1 in", values, "number_star1");
            return (Criteria) this;
        }

        public Criteria andNumber_star1NotIn(List<Integer> values) {
            addCriterion("number_star1 not in", values, "number_star1");
            return (Criteria) this;
        }

        public Criteria andNumber_star1Between(Integer value1, Integer value2) {
            addCriterion("number_star1 between", value1, value2, "number_star1");
            return (Criteria) this;
        }

        public Criteria andNumber_star1NotBetween(Integer value1, Integer value2) {
            addCriterion("number_star1 not between", value1, value2, "number_star1");
            return (Criteria) this;
        }

        public Criteria andNumber_toreadIsNull() {
            addCriterion("number_toread is null");
            return (Criteria) this;
        }

        public Criteria andNumber_toreadIsNotNull() {
            addCriterion("number_toread is not null");
            return (Criteria) this;
        }

        public Criteria andNumber_toreadEqualTo(Integer value) {
            addCriterion("number_toread =", value, "number_toread");
            return (Criteria) this;
        }

        public Criteria andNumber_toreadNotEqualTo(Integer value) {
            addCriterion("number_toread <>", value, "number_toread");
            return (Criteria) this;
        }

        public Criteria andNumber_toreadGreaterThan(Integer value) {
            addCriterion("number_toread >", value, "number_toread");
            return (Criteria) this;
        }

        public Criteria andNumber_toreadGreaterThanOrEqualTo(Integer value) {
            addCriterion("number_toread >=", value, "number_toread");
            return (Criteria) this;
        }

        public Criteria andNumber_toreadLessThan(Integer value) {
            addCriterion("number_toread <", value, "number_toread");
            return (Criteria) this;
        }

        public Criteria andNumber_toreadLessThanOrEqualTo(Integer value) {
            addCriterion("number_toread <=", value, "number_toread");
            return (Criteria) this;
        }

        public Criteria andNumber_toreadIn(List<Integer> values) {
            addCriterion("number_toread in", values, "number_toread");
            return (Criteria) this;
        }

        public Criteria andNumber_toreadNotIn(List<Integer> values) {
            addCriterion("number_toread not in", values, "number_toread");
            return (Criteria) this;
        }

        public Criteria andNumber_toreadBetween(Integer value1, Integer value2) {
            addCriterion("number_toread between", value1, value2, "number_toread");
            return (Criteria) this;
        }

        public Criteria andNumber_toreadNotBetween(Integer value1, Integer value2) {
            addCriterion("number_toread not between", value1, value2, "number_toread");
            return (Criteria) this;
        }

        public Criteria andNumber_readingIsNull() {
            addCriterion("number_reading is null");
            return (Criteria) this;
        }

        public Criteria andNumber_readingIsNotNull() {
            addCriterion("number_reading is not null");
            return (Criteria) this;
        }

        public Criteria andNumber_readingEqualTo(Integer value) {
            addCriterion("number_reading =", value, "number_reading");
            return (Criteria) this;
        }

        public Criteria andNumber_readingNotEqualTo(Integer value) {
            addCriterion("number_reading <>", value, "number_reading");
            return (Criteria) this;
        }

        public Criteria andNumber_readingGreaterThan(Integer value) {
            addCriterion("number_reading >", value, "number_reading");
            return (Criteria) this;
        }

        public Criteria andNumber_readingGreaterThanOrEqualTo(Integer value) {
            addCriterion("number_reading >=", value, "number_reading");
            return (Criteria) this;
        }

        public Criteria andNumber_readingLessThan(Integer value) {
            addCriterion("number_reading <", value, "number_reading");
            return (Criteria) this;
        }

        public Criteria andNumber_readingLessThanOrEqualTo(Integer value) {
            addCriterion("number_reading <=", value, "number_reading");
            return (Criteria) this;
        }

        public Criteria andNumber_readingIn(List<Integer> values) {
            addCriterion("number_reading in", values, "number_reading");
            return (Criteria) this;
        }

        public Criteria andNumber_readingNotIn(List<Integer> values) {
            addCriterion("number_reading not in", values, "number_reading");
            return (Criteria) this;
        }

        public Criteria andNumber_readingBetween(Integer value1, Integer value2) {
            addCriterion("number_reading between", value1, value2, "number_reading");
            return (Criteria) this;
        }

        public Criteria andNumber_readingNotBetween(Integer value1, Integer value2) {
            addCriterion("number_reading not between", value1, value2, "number_reading");
            return (Criteria) this;
        }

        public Criteria andNumber_readedIsNull() {
            addCriterion("number_readed is null");
            return (Criteria) this;
        }

        public Criteria andNumber_readedIsNotNull() {
            addCriterion("number_readed is not null");
            return (Criteria) this;
        }

        public Criteria andNumber_readedEqualTo(Integer value) {
            addCriterion("number_readed =", value, "number_readed");
            return (Criteria) this;
        }

        public Criteria andNumber_readedNotEqualTo(Integer value) {
            addCriterion("number_readed <>", value, "number_readed");
            return (Criteria) this;
        }

        public Criteria andNumber_readedGreaterThan(Integer value) {
            addCriterion("number_readed >", value, "number_readed");
            return (Criteria) this;
        }

        public Criteria andNumber_readedGreaterThanOrEqualTo(Integer value) {
            addCriterion("number_readed >=", value, "number_readed");
            return (Criteria) this;
        }

        public Criteria andNumber_readedLessThan(Integer value) {
            addCriterion("number_readed <", value, "number_readed");
            return (Criteria) this;
        }

        public Criteria andNumber_readedLessThanOrEqualTo(Integer value) {
            addCriterion("number_readed <=", value, "number_readed");
            return (Criteria) this;
        }

        public Criteria andNumber_readedIn(List<Integer> values) {
            addCriterion("number_readed in", values, "number_readed");
            return (Criteria) this;
        }

        public Criteria andNumber_readedNotIn(List<Integer> values) {
            addCriterion("number_readed not in", values, "number_readed");
            return (Criteria) this;
        }

        public Criteria andNumber_readedBetween(Integer value1, Integer value2) {
            addCriterion("number_readed between", value1, value2, "number_readed");
            return (Criteria) this;
        }

        public Criteria andNumber_readedNotBetween(Integer value1, Integer value2) {
            addCriterion("number_readed not between", value1, value2, "number_readed");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_online_info
     *
     * @mbggenerated do_not_delete_during_merge Sun May 19 11:22:56 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_online_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}