package cn.edu.ustb.dm.model;

import java.util.ArrayList;
import java.util.List;

public class BookPublishingInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_publishing_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_publishing_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_publishing_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_publishing_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public BookPublishingInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_publishing_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_publishing_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_publishing_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_publishing_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_publishing_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_publishing_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_publishing_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_publishing_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_publishing_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_publishing_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_publishing_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBook_idIsNull() {
            addCriterion("book_id is null");
            return (Criteria) this;
        }

        public Criteria andBook_idIsNotNull() {
            addCriterion("book_id is not null");
            return (Criteria) this;
        }

        public Criteria andBook_idEqualTo(Integer value) {
            addCriterion("book_id =", value, "book_id");
            return (Criteria) this;
        }

        public Criteria andBook_idNotEqualTo(Integer value) {
            addCriterion("book_id <>", value, "book_id");
            return (Criteria) this;
        }

        public Criteria andBook_idGreaterThan(Integer value) {
            addCriterion("book_id >", value, "book_id");
            return (Criteria) this;
        }

        public Criteria andBook_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("book_id >=", value, "book_id");
            return (Criteria) this;
        }

        public Criteria andBook_idLessThan(Integer value) {
            addCriterion("book_id <", value, "book_id");
            return (Criteria) this;
        }

        public Criteria andBook_idLessThanOrEqualTo(Integer value) {
            addCriterion("book_id <=", value, "book_id");
            return (Criteria) this;
        }

        public Criteria andBook_idIn(List<Integer> values) {
            addCriterion("book_id in", values, "book_id");
            return (Criteria) this;
        }

        public Criteria andBook_idNotIn(List<Integer> values) {
            addCriterion("book_id not in", values, "book_id");
            return (Criteria) this;
        }

        public Criteria andBook_idBetween(Integer value1, Integer value2) {
            addCriterion("book_id between", value1, value2, "book_id");
            return (Criteria) this;
        }

        public Criteria andBook_idNotBetween(Integer value1, Integer value2) {
            addCriterion("book_id not between", value1, value2, "book_id");
            return (Criteria) this;
        }

        public Criteria andIsbnIsNull() {
            addCriterion("isbn is null");
            return (Criteria) this;
        }

        public Criteria andIsbnIsNotNull() {
            addCriterion("isbn is not null");
            return (Criteria) this;
        }

        public Criteria andIsbnEqualTo(String value) {
            addCriterion("isbn =", value, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnNotEqualTo(String value) {
            addCriterion("isbn <>", value, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnGreaterThan(String value) {
            addCriterion("isbn >", value, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnGreaterThanOrEqualTo(String value) {
            addCriterion("isbn >=", value, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnLessThan(String value) {
            addCriterion("isbn <", value, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnLessThanOrEqualTo(String value) {
            addCriterion("isbn <=", value, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnLike(String value) {
            addCriterion("isbn like", value, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnNotLike(String value) {
            addCriterion("isbn not like", value, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnIn(List<String> values) {
            addCriterion("isbn in", values, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnNotIn(List<String> values) {
            addCriterion("isbn not in", values, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnBetween(String value1, String value2) {
            addCriterion("isbn between", value1, value2, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnNotBetween(String value1, String value2) {
            addCriterion("isbn not between", value1, value2, "isbn");
            return (Criteria) this;
        }

        public Criteria andBindingIsNull() {
            addCriterion("binding is null");
            return (Criteria) this;
        }

        public Criteria andBindingIsNotNull() {
            addCriterion("binding is not null");
            return (Criteria) this;
        }

        public Criteria andBindingEqualTo(String value) {
            addCriterion("binding =", value, "binding");
            return (Criteria) this;
        }

        public Criteria andBindingNotEqualTo(String value) {
            addCriterion("binding <>", value, "binding");
            return (Criteria) this;
        }

        public Criteria andBindingGreaterThan(String value) {
            addCriterion("binding >", value, "binding");
            return (Criteria) this;
        }

        public Criteria andBindingGreaterThanOrEqualTo(String value) {
            addCriterion("binding >=", value, "binding");
            return (Criteria) this;
        }

        public Criteria andBindingLessThan(String value) {
            addCriterion("binding <", value, "binding");
            return (Criteria) this;
        }

        public Criteria andBindingLessThanOrEqualTo(String value) {
            addCriterion("binding <=", value, "binding");
            return (Criteria) this;
        }

        public Criteria andBindingLike(String value) {
            addCriterion("binding like", value, "binding");
            return (Criteria) this;
        }

        public Criteria andBindingNotLike(String value) {
            addCriterion("binding not like", value, "binding");
            return (Criteria) this;
        }

        public Criteria andBindingIn(List<String> values) {
            addCriterion("binding in", values, "binding");
            return (Criteria) this;
        }

        public Criteria andBindingNotIn(List<String> values) {
            addCriterion("binding not in", values, "binding");
            return (Criteria) this;
        }

        public Criteria andBindingBetween(String value1, String value2) {
            addCriterion("binding between", value1, value2, "binding");
            return (Criteria) this;
        }

        public Criteria andBindingNotBetween(String value1, String value2) {
            addCriterion("binding not between", value1, value2, "binding");
            return (Criteria) this;
        }

        public Criteria andList_priceIsNull() {
            addCriterion("list_price is null");
            return (Criteria) this;
        }

        public Criteria andList_priceIsNotNull() {
            addCriterion("list_price is not null");
            return (Criteria) this;
        }

        public Criteria andList_priceEqualTo(String value) {
            addCriterion("list_price =", value, "list_price");
            return (Criteria) this;
        }

        public Criteria andList_priceNotEqualTo(String value) {
            addCriterion("list_price <>", value, "list_price");
            return (Criteria) this;
        }

        public Criteria andList_priceGreaterThan(String value) {
            addCriterion("list_price >", value, "list_price");
            return (Criteria) this;
        }

        public Criteria andList_priceGreaterThanOrEqualTo(String value) {
            addCriterion("list_price >=", value, "list_price");
            return (Criteria) this;
        }

        public Criteria andList_priceLessThan(String value) {
            addCriterion("list_price <", value, "list_price");
            return (Criteria) this;
        }

        public Criteria andList_priceLessThanOrEqualTo(String value) {
            addCriterion("list_price <=", value, "list_price");
            return (Criteria) this;
        }

        public Criteria andList_priceLike(String value) {
            addCriterion("list_price like", value, "list_price");
            return (Criteria) this;
        }

        public Criteria andList_priceNotLike(String value) {
            addCriterion("list_price not like", value, "list_price");
            return (Criteria) this;
        }

        public Criteria andList_priceIn(List<String> values) {
            addCriterion("list_price in", values, "list_price");
            return (Criteria) this;
        }

        public Criteria andList_priceNotIn(List<String> values) {
            addCriterion("list_price not in", values, "list_price");
            return (Criteria) this;
        }

        public Criteria andList_priceBetween(String value1, String value2) {
            addCriterion("list_price between", value1, value2, "list_price");
            return (Criteria) this;
        }

        public Criteria andList_priceNotBetween(String value1, String value2) {
            addCriterion("list_price not between", value1, value2, "list_price");
            return (Criteria) this;
        }

        public Criteria andPageIsNull() {
            addCriterion("page is null");
            return (Criteria) this;
        }

        public Criteria andPageIsNotNull() {
            addCriterion("page is not null");
            return (Criteria) this;
        }

        public Criteria andPageEqualTo(String value) {
            addCriterion("page =", value, "page");
            return (Criteria) this;
        }

        public Criteria andPageNotEqualTo(String value) {
            addCriterion("page <>", value, "page");
            return (Criteria) this;
        }

        public Criteria andPageGreaterThan(String value) {
            addCriterion("page >", value, "page");
            return (Criteria) this;
        }

        public Criteria andPageGreaterThanOrEqualTo(String value) {
            addCriterion("page >=", value, "page");
            return (Criteria) this;
        }

        public Criteria andPageLessThan(String value) {
            addCriterion("page <", value, "page");
            return (Criteria) this;
        }

        public Criteria andPageLessThanOrEqualTo(String value) {
            addCriterion("page <=", value, "page");
            return (Criteria) this;
        }

        public Criteria andPageLike(String value) {
            addCriterion("page like", value, "page");
            return (Criteria) this;
        }

        public Criteria andPageNotLike(String value) {
            addCriterion("page not like", value, "page");
            return (Criteria) this;
        }

        public Criteria andPageIn(List<String> values) {
            addCriterion("page in", values, "page");
            return (Criteria) this;
        }

        public Criteria andPageNotIn(List<String> values) {
            addCriterion("page not in", values, "page");
            return (Criteria) this;
        }

        public Criteria andPageBetween(String value1, String value2) {
            addCriterion("page between", value1, value2, "page");
            return (Criteria) this;
        }

        public Criteria andPageNotBetween(String value1, String value2) {
            addCriterion("page not between", value1, value2, "page");
            return (Criteria) this;
        }

        public Criteria andPublisherIsNull() {
            addCriterion("publisher is null");
            return (Criteria) this;
        }

        public Criteria andPublisherIsNotNull() {
            addCriterion("publisher is not null");
            return (Criteria) this;
        }

        public Criteria andPublisherEqualTo(String value) {
            addCriterion("publisher =", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherNotEqualTo(String value) {
            addCriterion("publisher <>", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherGreaterThan(String value) {
            addCriterion("publisher >", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherGreaterThanOrEqualTo(String value) {
            addCriterion("publisher >=", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherLessThan(String value) {
            addCriterion("publisher <", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherLessThanOrEqualTo(String value) {
            addCriterion("publisher <=", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherLike(String value) {
            addCriterion("publisher like", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherNotLike(String value) {
            addCriterion("publisher not like", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherIn(List<String> values) {
            addCriterion("publisher in", values, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherNotIn(List<String> values) {
            addCriterion("publisher not in", values, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherBetween(String value1, String value2) {
            addCriterion("publisher between", value1, value2, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherNotBetween(String value1, String value2) {
            addCriterion("publisher not between", value1, value2, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublication_dateIsNull() {
            addCriterion("publication_date is null");
            return (Criteria) this;
        }

        public Criteria andPublication_dateIsNotNull() {
            addCriterion("publication_date is not null");
            return (Criteria) this;
        }

        public Criteria andPublication_dateEqualTo(String value) {
            addCriterion("publication_date =", value, "publication_date");
            return (Criteria) this;
        }

        public Criteria andPublication_dateNotEqualTo(String value) {
            addCriterion("publication_date <>", value, "publication_date");
            return (Criteria) this;
        }

        public Criteria andPublication_dateGreaterThan(String value) {
            addCriterion("publication_date >", value, "publication_date");
            return (Criteria) this;
        }

        public Criteria andPublication_dateGreaterThanOrEqualTo(String value) {
            addCriterion("publication_date >=", value, "publication_date");
            return (Criteria) this;
        }

        public Criteria andPublication_dateLessThan(String value) {
            addCriterion("publication_date <", value, "publication_date");
            return (Criteria) this;
        }

        public Criteria andPublication_dateLessThanOrEqualTo(String value) {
            addCriterion("publication_date <=", value, "publication_date");
            return (Criteria) this;
        }

        public Criteria andPublication_dateLike(String value) {
            addCriterion("publication_date like", value, "publication_date");
            return (Criteria) this;
        }

        public Criteria andPublication_dateNotLike(String value) {
            addCriterion("publication_date not like", value, "publication_date");
            return (Criteria) this;
        }

        public Criteria andPublication_dateIn(List<String> values) {
            addCriterion("publication_date in", values, "publication_date");
            return (Criteria) this;
        }

        public Criteria andPublication_dateNotIn(List<String> values) {
            addCriterion("publication_date not in", values, "publication_date");
            return (Criteria) this;
        }

        public Criteria andPublication_dateBetween(String value1, String value2) {
            addCriterion("publication_date between", value1, value2, "publication_date");
            return (Criteria) this;
        }

        public Criteria andPublication_dateNotBetween(String value1, String value2) {
            addCriterion("publication_date not between", value1, value2, "publication_date");
            return (Criteria) this;
        }

        public Criteria andTitle_page_imagesIsNull() {
            addCriterion("title_page_images is null");
            return (Criteria) this;
        }

        public Criteria andTitle_page_imagesIsNotNull() {
            addCriterion("title_page_images is not null");
            return (Criteria) this;
        }

        public Criteria andTitle_page_imagesEqualTo(String value) {
            addCriterion("title_page_images =", value, "title_page_images");
            return (Criteria) this;
        }

        public Criteria andTitle_page_imagesNotEqualTo(String value) {
            addCriterion("title_page_images <>", value, "title_page_images");
            return (Criteria) this;
        }

        public Criteria andTitle_page_imagesGreaterThan(String value) {
            addCriterion("title_page_images >", value, "title_page_images");
            return (Criteria) this;
        }

        public Criteria andTitle_page_imagesGreaterThanOrEqualTo(String value) {
            addCriterion("title_page_images >=", value, "title_page_images");
            return (Criteria) this;
        }

        public Criteria andTitle_page_imagesLessThan(String value) {
            addCriterion("title_page_images <", value, "title_page_images");
            return (Criteria) this;
        }

        public Criteria andTitle_page_imagesLessThanOrEqualTo(String value) {
            addCriterion("title_page_images <=", value, "title_page_images");
            return (Criteria) this;
        }

        public Criteria andTitle_page_imagesLike(String value) {
            addCriterion("title_page_images like", value, "title_page_images");
            return (Criteria) this;
        }

        public Criteria andTitle_page_imagesNotLike(String value) {
            addCriterion("title_page_images not like", value, "title_page_images");
            return (Criteria) this;
        }

        public Criteria andTitle_page_imagesIn(List<String> values) {
            addCriterion("title_page_images in", values, "title_page_images");
            return (Criteria) this;
        }

        public Criteria andTitle_page_imagesNotIn(List<String> values) {
            addCriterion("title_page_images not in", values, "title_page_images");
            return (Criteria) this;
        }

        public Criteria andTitle_page_imagesBetween(String value1, String value2) {
            addCriterion("title_page_images between", value1, value2, "title_page_images");
            return (Criteria) this;
        }

        public Criteria andTitle_page_imagesNotBetween(String value1, String value2) {
            addCriterion("title_page_images not between", value1, value2, "title_page_images");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_publishing_info
     *
     * @mbggenerated do_not_delete_during_merge Sun May 19 11:22:56 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_publishing_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}