package cn.edu.ustb.dm.model;

public class BookAuthorInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_author_info.book_id
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer book_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_author_info.author_name
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private String author_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_author_info.introduction
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_author_info.content
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_author_info.book_id
     *
     * @return the value of book_author_info.book_id
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getBook_id() {
        return book_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_author_info.book_id
     *
     * @param book_id the value for book_author_info.book_id
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setBook_id(Integer book_id) {
        this.book_id = book_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_author_info.author_name
     *
     * @return the value of book_author_info.author_name
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getAuthor_name() {
        return author_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_author_info.author_name
     *
     * @param author_name the value for book_author_info.author_name
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setAuthor_name(String author_name) {
        this.author_name = author_name == null ? null : author_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_author_info.introduction
     *
     * @return the value of book_author_info.introduction
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_author_info.introduction
     *
     * @param introduction the value for book_author_info.introduction
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_author_info.content
     *
     * @return the value of book_author_info.content
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_author_info.content
     *
     * @param content the value for book_author_info.content
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}