package cn.edu.ustb.dm.model;

public class BookPublishingInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_publishing_info.book_id
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer book_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_publishing_info.isbn
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private String isbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_publishing_info.binding
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private String binding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_publishing_info.list_price
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private String list_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_publishing_info.page
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private String page;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_publishing_info.publisher
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private String publisher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_publishing_info.publication_date
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private String publication_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_publishing_info.title_page_images
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private String title_page_images;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_publishing_info.book_id
     *
     * @return the value of book_publishing_info.book_id
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getBook_id() {
        return book_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_publishing_info.book_id
     *
     * @param book_id the value for book_publishing_info.book_id
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setBook_id(Integer book_id) {
        this.book_id = book_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_publishing_info.isbn
     *
     * @return the value of book_publishing_info.isbn
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_publishing_info.isbn
     *
     * @param isbn the value for book_publishing_info.isbn
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn == null ? null : isbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_publishing_info.binding
     *
     * @return the value of book_publishing_info.binding
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getBinding() {
        return binding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_publishing_info.binding
     *
     * @param binding the value for book_publishing_info.binding
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setBinding(String binding) {
        this.binding = binding == null ? null : binding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_publishing_info.list_price
     *
     * @return the value of book_publishing_info.list_price
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getList_price() {
        return list_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_publishing_info.list_price
     *
     * @param list_price the value for book_publishing_info.list_price
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setList_price(String list_price) {
        this.list_price = list_price == null ? null : list_price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_publishing_info.page
     *
     * @return the value of book_publishing_info.page
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_publishing_info.page
     *
     * @param page the value for book_publishing_info.page
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setPage(String page) {
        this.page = page == null ? null : page.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_publishing_info.publisher
     *
     * @return the value of book_publishing_info.publisher
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_publishing_info.publisher
     *
     * @param publisher the value for book_publishing_info.publisher
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher == null ? null : publisher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_publishing_info.publication_date
     *
     * @return the value of book_publishing_info.publication_date
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getPublication_date() {
        return publication_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_publishing_info.publication_date
     *
     * @param publication_date the value for book_publishing_info.publication_date
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setPublication_date(String publication_date) {
        this.publication_date = publication_date == null ? null : publication_date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_publishing_info.title_page_images
     *
     * @return the value of book_publishing_info.title_page_images
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getTitle_page_images() {
        return title_page_images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_publishing_info.title_page_images
     *
     * @param title_page_images the value for book_publishing_info.title_page_images
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setTitle_page_images(String title_page_images) {
        this.title_page_images = title_page_images == null ? null : title_page_images.trim();
    }
}