package cn.edu.ustb.dm.model;

public class BookInfoWithBLOBs extends BookInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.DESCRIPTION
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private String DESCRIPTION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.DIRECTORY
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private String DIRECTORY;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.DESCRIPTION
     *
     * @return the value of book_info.DESCRIPTION
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.DESCRIPTION
     *
     * @param DESCRIPTION the value for book_info.DESCRIPTION
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION == null ? null : DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.DIRECTORY
     *
     * @return the value of book_info.DIRECTORY
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getDIRECTORY() {
        return DIRECTORY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.DIRECTORY
     *
     * @param DIRECTORY the value for book_info.DIRECTORY
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setDIRECTORY(String DIRECTORY) {
        this.DIRECTORY = DIRECTORY == null ? null : DIRECTORY.trim();
    }
}