package cn.edu.ustb.dm.model;

public class BookOnlineInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_online_info.book_id
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer book_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_online_info.number_review
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer number_review;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_online_info.number_star5
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer number_star5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_online_info.number_star4
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer number_star4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_online_info.number_star3
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer number_star3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_online_info.number_star2
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer number_star2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_online_info.number_star1
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer number_star1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_online_info.number_toread
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer number_toread;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_online_info.number_reading
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer number_reading;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_online_info.number_readed
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer number_readed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_online_info.book_id
     *
     * @return the value of book_online_info.book_id
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getBook_id() {
        return book_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_online_info.book_id
     *
     * @param book_id the value for book_online_info.book_id
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setBook_id(Integer book_id) {
        this.book_id = book_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_online_info.number_review
     *
     * @return the value of book_online_info.number_review
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getNumber_review() {
        return number_review;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_online_info.number_review
     *
     * @param number_review the value for book_online_info.number_review
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setNumber_review(Integer number_review) {
        this.number_review = number_review;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_online_info.number_star5
     *
     * @return the value of book_online_info.number_star5
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getNumber_star5() {
        return number_star5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_online_info.number_star5
     *
     * @param number_star5 the value for book_online_info.number_star5
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setNumber_star5(Integer number_star5) {
        this.number_star5 = number_star5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_online_info.number_star4
     *
     * @return the value of book_online_info.number_star4
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getNumber_star4() {
        return number_star4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_online_info.number_star4
     *
     * @param number_star4 the value for book_online_info.number_star4
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setNumber_star4(Integer number_star4) {
        this.number_star4 = number_star4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_online_info.number_star3
     *
     * @return the value of book_online_info.number_star3
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getNumber_star3() {
        return number_star3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_online_info.number_star3
     *
     * @param number_star3 the value for book_online_info.number_star3
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setNumber_star3(Integer number_star3) {
        this.number_star3 = number_star3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_online_info.number_star2
     *
     * @return the value of book_online_info.number_star2
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getNumber_star2() {
        return number_star2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_online_info.number_star2
     *
     * @param number_star2 the value for book_online_info.number_star2
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setNumber_star2(Integer number_star2) {
        this.number_star2 = number_star2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_online_info.number_star1
     *
     * @return the value of book_online_info.number_star1
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getNumber_star1() {
        return number_star1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_online_info.number_star1
     *
     * @param number_star1 the value for book_online_info.number_star1
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setNumber_star1(Integer number_star1) {
        this.number_star1 = number_star1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_online_info.number_toread
     *
     * @return the value of book_online_info.number_toread
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getNumber_toread() {
        return number_toread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_online_info.number_toread
     *
     * @param number_toread the value for book_online_info.number_toread
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setNumber_toread(Integer number_toread) {
        this.number_toread = number_toread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_online_info.number_reading
     *
     * @return the value of book_online_info.number_reading
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getNumber_reading() {
        return number_reading;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_online_info.number_reading
     *
     * @param number_reading the value for book_online_info.number_reading
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setNumber_reading(Integer number_reading) {
        this.number_reading = number_reading;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_online_info.number_readed
     *
     * @return the value of book_online_info.number_readed
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getNumber_readed() {
        return number_readed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_online_info.number_readed
     *
     * @param number_readed the value for book_online_info.number_readed
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setNumber_readed(Integer number_readed) {
        this.number_readed = number_readed;
    }
}