package cn.edu.ustb.dm.model;

import java.util.ArrayList;
import java.util.List;

public class BookAuthorRelationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_author_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_author_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_author_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public BookAuthorRelationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_author_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBOOK_IDIsNull() {
            addCriterion("BOOK_ID is null");
            return (Criteria) this;
        }

        public Criteria andBOOK_IDIsNotNull() {
            addCriterion("BOOK_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBOOK_IDEqualTo(Integer value) {
            addCriterion("BOOK_ID =", value, "BOOK_ID");
            return (Criteria) this;
        }

        public Criteria andBOOK_IDNotEqualTo(Integer value) {
            addCriterion("BOOK_ID <>", value, "BOOK_ID");
            return (Criteria) this;
        }

        public Criteria andBOOK_IDGreaterThan(Integer value) {
            addCriterion("BOOK_ID >", value, "BOOK_ID");
            return (Criteria) this;
        }

        public Criteria andBOOK_IDGreaterThanOrEqualTo(Integer value) {
            addCriterion("BOOK_ID >=", value, "BOOK_ID");
            return (Criteria) this;
        }

        public Criteria andBOOK_IDLessThan(Integer value) {
            addCriterion("BOOK_ID <", value, "BOOK_ID");
            return (Criteria) this;
        }

        public Criteria andBOOK_IDLessThanOrEqualTo(Integer value) {
            addCriterion("BOOK_ID <=", value, "BOOK_ID");
            return (Criteria) this;
        }

        public Criteria andBOOK_IDIn(List<Integer> values) {
            addCriterion("BOOK_ID in", values, "BOOK_ID");
            return (Criteria) this;
        }

        public Criteria andBOOK_IDNotIn(List<Integer> values) {
            addCriterion("BOOK_ID not in", values, "BOOK_ID");
            return (Criteria) this;
        }

        public Criteria andBOOK_IDBetween(Integer value1, Integer value2) {
            addCriterion("BOOK_ID between", value1, value2, "BOOK_ID");
            return (Criteria) this;
        }

        public Criteria andBOOK_IDNotBetween(Integer value1, Integer value2) {
            addCriterion("BOOK_ID not between", value1, value2, "BOOK_ID");
            return (Criteria) this;
        }

        public Criteria andAUTHOR_IDIsNull() {
            addCriterion("AUTHOR_ID is null");
            return (Criteria) this;
        }

        public Criteria andAUTHOR_IDIsNotNull() {
            addCriterion("AUTHOR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAUTHOR_IDEqualTo(Integer value) {
            addCriterion("AUTHOR_ID =", value, "AUTHOR_ID");
            return (Criteria) this;
        }

        public Criteria andAUTHOR_IDNotEqualTo(Integer value) {
            addCriterion("AUTHOR_ID <>", value, "AUTHOR_ID");
            return (Criteria) this;
        }

        public Criteria andAUTHOR_IDGreaterThan(Integer value) {
            addCriterion("AUTHOR_ID >", value, "AUTHOR_ID");
            return (Criteria) this;
        }

        public Criteria andAUTHOR_IDGreaterThanOrEqualTo(Integer value) {
            addCriterion("AUTHOR_ID >=", value, "AUTHOR_ID");
            return (Criteria) this;
        }

        public Criteria andAUTHOR_IDLessThan(Integer value) {
            addCriterion("AUTHOR_ID <", value, "AUTHOR_ID");
            return (Criteria) this;
        }

        public Criteria andAUTHOR_IDLessThanOrEqualTo(Integer value) {
            addCriterion("AUTHOR_ID <=", value, "AUTHOR_ID");
            return (Criteria) this;
        }

        public Criteria andAUTHOR_IDIn(List<Integer> values) {
            addCriterion("AUTHOR_ID in", values, "AUTHOR_ID");
            return (Criteria) this;
        }

        public Criteria andAUTHOR_IDNotIn(List<Integer> values) {
            addCriterion("AUTHOR_ID not in", values, "AUTHOR_ID");
            return (Criteria) this;
        }

        public Criteria andAUTHOR_IDBetween(Integer value1, Integer value2) {
            addCriterion("AUTHOR_ID between", value1, value2, "AUTHOR_ID");
            return (Criteria) this;
        }

        public Criteria andAUTHOR_IDNotBetween(Integer value1, Integer value2) {
            addCriterion("AUTHOR_ID not between", value1, value2, "AUTHOR_ID");
            return (Criteria) this;
        }

        public Criteria andAUTHOR_TYPE_IDIsNull() {
            addCriterion("AUTHOR_TYPE_ID is null");
            return (Criteria) this;
        }

        public Criteria andAUTHOR_TYPE_IDIsNotNull() {
            addCriterion("AUTHOR_TYPE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAUTHOR_TYPE_IDEqualTo(Integer value) {
            addCriterion("AUTHOR_TYPE_ID =", value, "AUTHOR_TYPE_ID");
            return (Criteria) this;
        }

        public Criteria andAUTHOR_TYPE_IDNotEqualTo(Integer value) {
            addCriterion("AUTHOR_TYPE_ID <>", value, "AUTHOR_TYPE_ID");
            return (Criteria) this;
        }

        public Criteria andAUTHOR_TYPE_IDGreaterThan(Integer value) {
            addCriterion("AUTHOR_TYPE_ID >", value, "AUTHOR_TYPE_ID");
            return (Criteria) this;
        }

        public Criteria andAUTHOR_TYPE_IDGreaterThanOrEqualTo(Integer value) {
            addCriterion("AUTHOR_TYPE_ID >=", value, "AUTHOR_TYPE_ID");
            return (Criteria) this;
        }

        public Criteria andAUTHOR_TYPE_IDLessThan(Integer value) {
            addCriterion("AUTHOR_TYPE_ID <", value, "AUTHOR_TYPE_ID");
            return (Criteria) this;
        }

        public Criteria andAUTHOR_TYPE_IDLessThanOrEqualTo(Integer value) {
            addCriterion("AUTHOR_TYPE_ID <=", value, "AUTHOR_TYPE_ID");
            return (Criteria) this;
        }

        public Criteria andAUTHOR_TYPE_IDIn(List<Integer> values) {
            addCriterion("AUTHOR_TYPE_ID in", values, "AUTHOR_TYPE_ID");
            return (Criteria) this;
        }

        public Criteria andAUTHOR_TYPE_IDNotIn(List<Integer> values) {
            addCriterion("AUTHOR_TYPE_ID not in", values, "AUTHOR_TYPE_ID");
            return (Criteria) this;
        }

        public Criteria andAUTHOR_TYPE_IDBetween(Integer value1, Integer value2) {
            addCriterion("AUTHOR_TYPE_ID between", value1, value2, "AUTHOR_TYPE_ID");
            return (Criteria) this;
        }

        public Criteria andAUTHOR_TYPE_IDNotBetween(Integer value1, Integer value2) {
            addCriterion("AUTHOR_TYPE_ID not between", value1, value2, "AUTHOR_TYPE_ID");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_author_relation
     *
     * @mbggenerated do_not_delete_during_merge Sun May 19 11:22:56 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_author_relation
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}