package cn.edu.ustb.dm.model;

public class NationalityInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nationality_info.NATIONALITY_ID
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer NATIONALITY_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nationality_info.NATIONALITY_NAME
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private String NATIONALITY_NAME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nationality_info.NATIONALITY_ID
     *
     * @return the value of nationality_info.NATIONALITY_ID
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getNATIONALITY_ID() {
        return NATIONALITY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nationality_info.NATIONALITY_ID
     *
     * @param NATIONALITY_ID the value for nationality_info.NATIONALITY_ID
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setNATIONALITY_ID(Integer NATIONALITY_ID) {
        this.NATIONALITY_ID = NATIONALITY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nationality_info.NATIONALITY_NAME
     *
     * @return the value of nationality_info.NATIONALITY_NAME
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getNATIONALITY_NAME() {
        return NATIONALITY_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nationality_info.NATIONALITY_NAME
     *
     * @param NATIONALITY_NAME the value for nationality_info.NATIONALITY_NAME
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setNATIONALITY_NAME(String NATIONALITY_NAME) {
        this.NATIONALITY_NAME = NATIONALITY_NAME == null ? null : NATIONALITY_NAME.trim();
    }
}