package cn.edu.ustb.dm.model;

import java.util.ArrayList;
import java.util.List;

public class TagInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tag_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tag_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tag_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public TagInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tag_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTAG_IDIsNull() {
            addCriterion("TAG_ID is null");
            return (Criteria) this;
        }

        public Criteria andTAG_IDIsNotNull() {
            addCriterion("TAG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTAG_IDEqualTo(Integer value) {
            addCriterion("TAG_ID =", value, "TAG_ID");
            return (Criteria) this;
        }

        public Criteria andTAG_IDNotEqualTo(Integer value) {
            addCriterion("TAG_ID <>", value, "TAG_ID");
            return (Criteria) this;
        }

        public Criteria andTAG_IDGreaterThan(Integer value) {
            addCriterion("TAG_ID >", value, "TAG_ID");
            return (Criteria) this;
        }

        public Criteria andTAG_IDGreaterThanOrEqualTo(Integer value) {
            addCriterion("TAG_ID >=", value, "TAG_ID");
            return (Criteria) this;
        }

        public Criteria andTAG_IDLessThan(Integer value) {
            addCriterion("TAG_ID <", value, "TAG_ID");
            return (Criteria) this;
        }

        public Criteria andTAG_IDLessThanOrEqualTo(Integer value) {
            addCriterion("TAG_ID <=", value, "TAG_ID");
            return (Criteria) this;
        }

        public Criteria andTAG_IDIn(List<Integer> values) {
            addCriterion("TAG_ID in", values, "TAG_ID");
            return (Criteria) this;
        }

        public Criteria andTAG_IDNotIn(List<Integer> values) {
            addCriterion("TAG_ID not in", values, "TAG_ID");
            return (Criteria) this;
        }

        public Criteria andTAG_IDBetween(Integer value1, Integer value2) {
            addCriterion("TAG_ID between", value1, value2, "TAG_ID");
            return (Criteria) this;
        }

        public Criteria andTAG_IDNotBetween(Integer value1, Integer value2) {
            addCriterion("TAG_ID not between", value1, value2, "TAG_ID");
            return (Criteria) this;
        }

        public Criteria andNAMEIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNAMEIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNAMEEqualTo(String value) {
            addCriterion("NAME =", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMENotEqualTo(String value) {
            addCriterion("NAME <>", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMEGreaterThan(String value) {
            addCriterion("NAME >", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMEGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMELessThan(String value) {
            addCriterion("NAME <", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMELessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMELike(String value) {
            addCriterion("NAME like", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMENotLike(String value) {
            addCriterion("NAME not like", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMEIn(List<String> values) {
            addCriterion("NAME in", values, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMENotIn(List<String> values) {
            addCriterion("NAME not in", values, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMEBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMENotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "NAME");
            return (Criteria) this;
        }

        public Criteria andCOUNTIsNull() {
            addCriterion("COUNT is null");
            return (Criteria) this;
        }

        public Criteria andCOUNTIsNotNull() {
            addCriterion("COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andCOUNTEqualTo(Integer value) {
            addCriterion("COUNT =", value, "COUNT");
            return (Criteria) this;
        }

        public Criteria andCOUNTNotEqualTo(Integer value) {
            addCriterion("COUNT <>", value, "COUNT");
            return (Criteria) this;
        }

        public Criteria andCOUNTGreaterThan(Integer value) {
            addCriterion("COUNT >", value, "COUNT");
            return (Criteria) this;
        }

        public Criteria andCOUNTGreaterThanOrEqualTo(Integer value) {
            addCriterion("COUNT >=", value, "COUNT");
            return (Criteria) this;
        }

        public Criteria andCOUNTLessThan(Integer value) {
            addCriterion("COUNT <", value, "COUNT");
            return (Criteria) this;
        }

        public Criteria andCOUNTLessThanOrEqualTo(Integer value) {
            addCriterion("COUNT <=", value, "COUNT");
            return (Criteria) this;
        }

        public Criteria andCOUNTIn(List<Integer> values) {
            addCriterion("COUNT in", values, "COUNT");
            return (Criteria) this;
        }

        public Criteria andCOUNTNotIn(List<Integer> values) {
            addCriterion("COUNT not in", values, "COUNT");
            return (Criteria) this;
        }

        public Criteria andCOUNTBetween(Integer value1, Integer value2) {
            addCriterion("COUNT between", value1, value2, "COUNT");
            return (Criteria) this;
        }

        public Criteria andCOUNTNotBetween(Integer value1, Integer value2) {
            addCriterion("COUNT not between", value1, value2, "COUNT");
            return (Criteria) this;
        }

        public Criteria andLEVELIsNull() {
            addCriterion("LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andLEVELIsNotNull() {
            addCriterion("LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andLEVELEqualTo(Integer value) {
            addCriterion("LEVEL =", value, "LEVEL");
            return (Criteria) this;
        }

        public Criteria andLEVELNotEqualTo(Integer value) {
            addCriterion("LEVEL <>", value, "LEVEL");
            return (Criteria) this;
        }

        public Criteria andLEVELGreaterThan(Integer value) {
            addCriterion("LEVEL >", value, "LEVEL");
            return (Criteria) this;
        }

        public Criteria andLEVELGreaterThanOrEqualTo(Integer value) {
            addCriterion("LEVEL >=", value, "LEVEL");
            return (Criteria) this;
        }

        public Criteria andLEVELLessThan(Integer value) {
            addCriterion("LEVEL <", value, "LEVEL");
            return (Criteria) this;
        }

        public Criteria andLEVELLessThanOrEqualTo(Integer value) {
            addCriterion("LEVEL <=", value, "LEVEL");
            return (Criteria) this;
        }

        public Criteria andLEVELIn(List<Integer> values) {
            addCriterion("LEVEL in", values, "LEVEL");
            return (Criteria) this;
        }

        public Criteria andLEVELNotIn(List<Integer> values) {
            addCriterion("LEVEL not in", values, "LEVEL");
            return (Criteria) this;
        }

        public Criteria andLEVELBetween(Integer value1, Integer value2) {
            addCriterion("LEVEL between", value1, value2, "LEVEL");
            return (Criteria) this;
        }

        public Criteria andLEVELNotBetween(Integer value1, Integer value2) {
            addCriterion("LEVEL not between", value1, value2, "LEVEL");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tag_info
     *
     * @mbggenerated do_not_delete_during_merge Sun May 19 11:22:56 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tag_info
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}