package cn.edu.ustb.dm.model;

public class TagInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_info.TAG_ID
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer TAG_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_info.NAME
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private String NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_info.COUNT
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer COUNT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_info.LEVEL
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    private Integer LEVEL;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_info.TAG_ID
     *
     * @return the value of tag_info.TAG_ID
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getTAG_ID() {
        return TAG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_info.TAG_ID
     *
     * @param TAG_ID the value for tag_info.TAG_ID
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setTAG_ID(Integer TAG_ID) {
        this.TAG_ID = TAG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_info.NAME
     *
     * @return the value of tag_info.NAME
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public String getNAME() {
        return NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_info.NAME
     *
     * @param NAME the value for tag_info.NAME
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setNAME(String NAME) {
        this.NAME = NAME == null ? null : NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_info.COUNT
     *
     * @return the value of tag_info.COUNT
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getCOUNT() {
        return COUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_info.COUNT
     *
     * @param COUNT the value for tag_info.COUNT
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setCOUNT(Integer COUNT) {
        this.COUNT = COUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_info.LEVEL
     *
     * @return the value of tag_info.LEVEL
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public Integer getLEVEL() {
        return LEVEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_info.LEVEL
     *
     * @param LEVEL the value for tag_info.LEVEL
     *
     * @mbggenerated Sun May 19 11:22:56 CST 2013
     */
    public void setLEVEL(Integer LEVEL) {
        this.LEVEL = LEVEL;
    }
}